fares-data-build-tool/create-data

.circleci/config.yml, Makefile, repos/fdbt-netex-output/src/netex-validator/package-lock.json, repos/fdbt-site/cypress_tests/package-lock.json, repos/fdbt-site/package-lock.json, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/definePassengerType.ts, repos/fdbt-site/tests/pages/api/definePassengerType.test.ts
=> fix: Fix loading groups from DB

repos/fdbt-site/src/pages/api/apiUtils/userData.ts, repos/fdbt-site/src/pages/salesOfferPackages.tsx, repos/fdbt-site/tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap, repos/fdbt-site/tests/pages/api/multipleProducts.test.ts
-   Add the digital option for TfL tickets
-   Check the digital option is present and maps to electronic_document …
=> feat: CFD-284 Add digital ticket option

repos/fdbt-site/cypress_tests/cypress/integration/carnet/flatFare.ts, repos/fdbt-site/cypress_tests/cypress/integration/carnet/period.ts, repos/fdbt-site/cypress_tests/cypress/integration/carnet/pointToPoint.ts, repos/fdbt-site/cypress_tests/cypress/integration/carnet/school.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/package-lock.json, repos/fdbt-site/src/pages/multipleProducts.tsx, repos/fdbt-site/tests/pages/__snapshots__/multipleProducts.test.tsx.snap, repos/fdbt-site/tsconfig.json
-   Add test coverage for Carnet fare types
-   Let the UI tests run
-   [ ] …
=> test: CFD-283 UI Tests for carnets

repos/fdbt-site/cypress_tests/cypress/integration/period.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/apiUtils/userData.ts, repos/fdbt-site/src/pages/api/csvZoneUpload.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/api/ticketRepresentation.ts, repos/fdbt-site/src/pages/serviceList.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/tests/pages/__snapshots__/serviceList.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/ticketRepresentation.test.tsx.snap, repos/fdbt-site/tests/pages/serviceList.test.tsx, repos/fdbt-site/tests/pages/ticketConfirmation.test.tsx, repos/fdbt-site/tests/pages/ticketRepresentation.test.tsx
-   Add the UI for Hybrid tickets
-   Create a hybrid period ticket and check the matching JSON …
=> feat: CFD-281 Hybrid ticket UI

repos/fdbt-site/cypress_tests/cypress/integration/carnet/scheme.ts, repos/fdbt-site/cypress_tests/cypress/integration/multiOperator.ts, repos/fdbt-site/cypress_tests/cypress/integration/scheme.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/api/fareType.ts, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap, repos/fdbt-site/tests/pages/api/fareType.test.ts
-   To make the changes to the UI to allow scheme operators to make carnet tickets.
-   Run locally and use the disable auth = scheme feature to log in as a scheme operator. Attempt to use the new journeys.
-   [ ] ci - Changes to our CI configuration files and …
=> feat: scheme operator flat fares UI 

fdbt-dev/scripts/generate_validate_all_netex.sh, repos/fdbt-site/src/pages/ticketRepresentation.tsx
-   Disable P2P Period for multi op
-   Check that there is no point to point option for a period multi operator ticket …
=> feat: Disable P2P Period for multi op

fdbt-dev/Makefile, fdbt-dev/data/matchingData/schemeCarnetFlatFare.json, fdbt-dev/data/matchingData/schemeCarnetPeriod.json, fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeCarnetPeriod.xml
-   Adding the files generated for scheme carnet journeys used for manual validation that the carnet information is contained in the netex
-   N/A …
=> feat: CFD-324 Validate scheme carnet netex

fdbt-dev/README.md, package-lock.json, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-site/package.json
-   made change to allow multiple sales offers packages to be referenced in the neTEx
- CD to neTEx ouput and run npm run test
- Create multiple sales offer packages, check that each one is being referenced against the product by creating the netex and ensure that all the sales offer packages selected are matched against the product
-   [ ] build - Changes that affect the build …
=> fix: Period Products with more than one SOP now have the additional SOP's referenced

repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap, repos/fdbt-site/tests/pages/fareType.test.tsx
-   Enable carnet scheme fares
=> feat: CFD-324 Enable carnet scheme fares

.circleci/config.yml
=> fix: CFD-287 slack circle ci notifications

.circleci/config.yml
fix: CFD-287 slack circle ci notifications (#39)
=> Pre-prod release

repos/fdbt-netex-output/serverless.yml
-   Update IAM permissions in order to allow the handler to push to the Slack Alerts SNS topic.
-   [ ] …
=> update iam permissions to allow push to slack alert sns topic

.circleci/config.yml
=> fix:CFD-287 Slack Circle CI Refactor

repos/fdbt-site/src/pages/inputMethod.tsx, repos/fdbt-site/tests/pages/__snapshots__/inputMethod.test.tsx.snap
-   Remove the interactive map input type
-   Check the interactive map input option is gone
=> feat: CFD-334 Remove coming soon input type

repos/fdbt-netex-output/src/netex-convertor/handler.test.ts, repos/fdbt-netex-output/src/netex-convertor/handler.ts, repos/fdbt-netex-output/src/netex-validator/main.py
=> Feat: CFD-289 add a subject to the message

repos/fdbt-site/src/components/DeleteSOPButton.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/tests/components/__snapshots__/DeleteSOPButton.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/selectSalesOfferPackage.test.tsx.snap
-   Improve UI for multiple product SOPs
-   Do a multi product journey and look at the select SOP page and check it's layout correctly
-   Repeat for a single journey with no set of multiple products …
=> feat: CFD-316 Improve UI for multiple product SOPs

repos/fdbt-netex-output/src/netex-convertor/handler.ts, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts, repos/fdbt-netex-output/src/types/index.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts
-   Adds labels for Scheme and Carnet to the log that Grafana uses to spilt tickets by type
-   Need to use the Grafana dashboard that breaks down ticket types for Netex
-   Check that Scheme and Carnet tickets are identified
-   NOTE: IWBusCo is filtered out
-   [ ] …
=> feat: CFD-332 Add Carnet and Scheme info to Grafana log

repos/fdbt-site/.eslintrc.js, repos/fdbt-site/next-env.d.ts, repos/fdbt-site/package.json, repos/fdbt-site/src/components/FormElementWrapper.tsx, repos/fdbt-site/src/components/RadioConditionalInput.tsx, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/selectSalesOfferPackage.ts, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/utils/index.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/testData/mockData.ts
=> refactor: CFD-290 Add some more ideal linting fixes

repos/fdbt-site/cypress_tests/.eslintrc.js, repos/fdbt-site/cypress_tests/browserstack.json, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/cypress_tests/package-lock.json, repos/fdbt-site/cypress_tests/package.json, repos/fdbt-site/src/pages/ticketRepresentation.tsx
-   Turn on hybrid in prod
-   Test in prod
-   [ ] revert - Reverts a previous …
=> feat: CFD-282 Enable Hybrid

fdbt-dev/Makefile, fdbt-dev/data/matchingData/flatFareWithSopPrices.json, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, repos/fdbt-netex-output/.eslintrc.js, repos/fdbt-netex-output/serverless.yml, repos/fdbt-netex-output/src/netex-convertor/handler.ts, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/run-local.ts, repos/fdbt-netex-output/src/types/index.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/interfaces/typeGuards.ts, repos/fdbt-site/src/pages/api/describeSalesOfferPackage.ts, repos/fdbt-site/src/pages/api/selectSalesOfferPackage.ts, repos/fdbt-site/src/pages/describeSalesOfferPackage.tsx, repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/api/describeSalesOfferPackage.test.ts, repos/fdbt-site/tests/pages/describeSalesOfferPackage.test.tsx, repos/fdbt-site/tests/pages/selectSalesOfferPackage.test.tsx, repos/fdbt-site/tests/testData/mockData.ts, shared/matchingJsonTypes.d.ts, shared/tsconfig.json
-   Netex updates for prices per SOP
-   Complete any Period or Flat Fare journey
-   When you get to the Sales Offer Package page tick multiple options
-   Change the prices for some of the options and remember the values
-   Generate the Netex and check that the price per SOP is included as the value 
-   [ ] build - Changes that affect the build system or external dependencies …
=> feat: CFD-306 Netex updates for prices per SOP

.circleci/config.yml, site.Dockerfile
-   Copy shared files for docker build
-   Build should pass …
=> fix: CFD-305 Copy shared files for docker build

.circleci/config.yml
-   Revert to docker build and push standard job
=> fix: CFD-305 Revert to docker build and push standard job

repos/fdbt-site/.eslintrc.js, repos/fdbt-site/src/components/SettingOverview.tsx, repos/fdbt-site/src/design/modules/_pages.scss, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/layout/Navigation.tsx, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap, repos/fdbt-site/tests/pages/globalSettings.test.tsx
feat: completed passenger types part of overview page
=> Pre Prod Release

repos/fdbt-site/next.config.js
=> feat: CFD-297 turn on source maps

repos/fdbt-site/.eslintrc.js, repos/fdbt-site/next.config.js, repos/fdbt-site/src/components/Help.tsx, repos/fdbt-site/src/pages/_error.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/components/__snapshots__/Help.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/_error.test.tsx.snap
-   Hopefully a fix for viewPassengerTypes page on Test.
-   Visit the page and make sure it loads fine.
-   [ ] chore - Other changes that don't …
=> feat: cfd-297 array check before map call

repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/pages/ticketRepresentation.tsx
-   Turn on the feature flags
-   Check the features are enabled in PROD
-   [ ] …
=> feat: CFD-267 Enable P2P Period and SOP price

repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/tests/pages/salesConfirmation.test.tsx
Included the details of each SOP on the /salesConfirmation page, i.e.:
- Purchase locations
- Payment methods
- Ticket formats
-   Add some SOP and proceed to sales conformation page
-   Check "Purchase locations", "Payment methods" and "Ticket formats" are displayed correctly in non camelcase
-   [ ] build - Changes that affect the build system or external dependencies (example …
=> feat: cfd-165 sop contents confirmation

fdbt-aws/cloudformation/service/eu-west-2/s3.yml, repos/fdbt-site/src/design/modules/_cards.scss, repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/pages/salesConfirmation.test.tsx, repos/fdbt-site/tests/pages/selectSalesOfferPackage.test.tsx
feat: CFD-165 sop contents confirmation
fix: CFD-355 passenger page design issues
feat: CFD-167 remove the bucket lifecycle policy and fix linting issues
=> Preprod Release

repos/fdbt-site/package-lock.json, repos/fdbt-site/package.json, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/managePassengerGroup.ts, repos/fdbt-site/src/pages/api/managePassengerTypes.ts, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/api/managePassengerGroup.test.ts, repos/fdbt-site/tests/pages/managePassengerGroup.test.tsx, repos/fdbt-site/tests/pages/viewPassengerTypes.test.tsx
-   To allow the user to create groups from previously made passenger types, and also delete them groups.
-   Run locally and use the UI in global settings to create and delete passenger groups.
-   [ ] ci - Changes to our CI configuration files and scripts (example …
=> feat: create and delete passenger groups

Makefile, repos/fdbt-netex-output/package-lock.json, repos/fdbt-netex-output/package.json, repos/fdbt-netex-output/src/netex-validator/package-lock.json, repos/fdbt-reference-data-service/src/retrievers/package-lock.json, repos/fdbt-reference-data-service/src/uploaders/package-lock.json
=> build: fix npm audit issues

repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx, repos/fdbt-site/src/components/Help.tsx, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/components/__snapshots__/Help.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap
-   To fix some visual bugs around groups.
-   Check the pages look OK.
-   [ ] …
=> fix: Fixed visual issues

repos/fdbt-site/cypress_tests/cypress/integration/carnet/flatFare.ts, repos/fdbt-site/cypress_tests/cypress/integration/flatFare.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/components/Help.tsx, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/apiUtils/index.ts, repos/fdbt-site/src/pages/api/apiUtils/userData.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/carnetFareType.tsx, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/components/__snapshots__/Help.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/carnetFareType.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap, repos/fdbt-site/tests/pages/api/apiUtils/index.test.ts, repos/fdbt-site/tests/pages/api/apiUtils/userData.test.ts, repos/fdbt-site/tests/pages/api/multipleOperatorsServiceList.test.ts, repos/fdbt-site/tests/pages/api/multipleProducts.test.ts, repos/fdbt-site/tests/pages/api/passengerType.test.ts, repos/fdbt-site/tests/pages/api/salesConfirmation.test.ts, repos/fdbt-site/tests/pages/api/selectSalesOfferPackage.test.ts, repos/fdbt-site/tests/pages/ticketConfirmation.test.tsx, repos/fdbt-site/tests/testData/mockData.ts, shared/matchingJsonTypes.ts
-   Add the short hop geoZone hopper type to the UI
-   Complete a Flat Fare multiple services journey
-   Complete a Flat Fare geo zone journey
-   Make sure that flat fare still works for schools / schemes / carnets
-   [ ] ci - Changes to our CI configuration files …
=> feat: CFD-363 Short hop fare type UI

repos/fdbt-site/src/pages/viewTimeRestrictions.tsx, repos/fdbt-site/tests/pages/__snapshots__/viewTimeRestrictions.test.tsx.snap, repos/fdbt-site/tests/pages/viewTimeRestrictions.test.tsx
-   Removing the word 'Individual' from the view time restrictions page.
-   Navigate to page. …
=> fix: Removed individual from view time restrictions page

repos/fdbt-site/src/pages/api/apiUtils/index.ts
-   Enable the feature on prod
-   Ensure netex gets generated on prod.
-   [ ] …
=> feat: cfd-364 enable feature on prod

repos/fdbt-site/.eslintrc.js, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/design/modules/_cards.scss, repos/fdbt-site/src/design/modules/_components.scss, repos/fdbt-site/src/design/modules/_layout.scss, repos/fdbt-site/src/layout/GlobalSettingReturnHeader.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx
-   Replace inline styles that were not working with classes
-   Check that the styling on the following pages looks correct
- Select sales offer package
- Select passenger type (new one with Global Settings turned on)
-   [ ] ci - Changes to our CI configuration …
=> fix: CFD-330 Replace inline styles that were not working with classes

repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/api/definePassengerType.ts, repos/fdbt-site/src/pages/api/passengerType.ts, repos/fdbt-site/src/pages/api/selectPassengerType.ts, repos/fdbt-site/src/pages/fareConfirmation.tsx, repos/fdbt-site/src/pages/managePassengerTypes.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/fareConfirmation.test.tsx
- fix school journey after passenger types broke it
-   Run UI tests
-   [ ] …
=> Fix:CFD-381 Fix school journey passenger types

repos/fdbt-site/src/pages/api/carnetFareType.ts
-   Fix the school carnet journey for new passenger type screen
-   Run through the carnet school journey and check it completes successfully
-   [ …
=> fix: CFD-381 Fix carnet school journeys as well

repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/managePassengerTypes.ts, repos/fdbt-site/src/pages/api/manageTimeRestriction.ts, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/managePassengerTypes.tsx, repos/fdbt-site/src/pages/manageTimeRestriction.tsx, repos/fdbt-site/src/pages/viewTimeRestrictions.tsx, repos/fdbt-site/src/utils/globalSettings.ts, repos/fdbt-site/tests/pages/__snapshots__/manageTimeRestriction.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewTimeRestrictions.test.tsx.snap, repos/fdbt-site/tests/pages/api/managePassengerTypes.test.ts, repos/fdbt-site/tests/pages/api/manageTimeRestriction.test.ts, repos/fdbt-site/tests/pages/manageTimeRestriction.test.tsx
-   Edit time restrictions in global settings
-   Test that you can create and Edit Time Restrictions 
-   Smoke testing around passenger types in global settings due to refactoring
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: …
=> feat: CFD-368 Edit time restrictions

repos/fdbt-site/cypress_tests/cypress/integration/globalSettings/passengerTypes.ts, repos/fdbt-site/cypress_tests/cypress/support/globalSettings.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap
-   E2E tests for global settings passenger types 
-   See if E2E tests pass
- …
=> test: CFD-377 E2E tests for global settings passenger types

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/deletePurchaseMethod.ts
-   To allow users to delete purchase methods through global settings.
-   Run locally and create a purchase method, then delete it.
-   [ ] chore …
=> feat: delete purchase methods

repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/managePurchaseMethod.ts, repos/fdbt-site/src/pages/api/salesOfferPackages.ts, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/src/pages/managePurchaseMethod.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/utils/index.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePurchaseMethod.test.tsx.snap, repos/fdbt-site/tests/pages/api/managePurchaseMethod.test.ts, repos/fdbt-site/tests/pages/managePurchaseMethod.test.tsx, shared/matchingJsonTypes.ts
-   Manage purchase methods in global settings
-   Create some purchase methods in global setting …
=> feat: CFD-312 Create purchase methods in global settings

fdbt-aws/sql/z.createUsers.sql, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/managePurchaseMethod.ts, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/managePurchaseMethod.tsx, repos/fdbt-site/src/pages/manageTimeRestriction.tsx, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePurchaseMethod.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageTimeRestriction.test.tsx.snap, repos/fdbt-site/tests/pages/api/managePurchaseMethod.test.ts
-   Edit purchase methods in global settings
-   Check that you can create and edit purchase methods in global settings …
=> feat: CFD-382 Edit purchase methods in global settings

repos/fdbt-site/cypress_tests/cypress/integration/single.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/api/defineTimeRestrictions.ts, repos/fdbt-site/src/pages/defineTimeRestrictions.tsx, repos/fdbt-site/src/pages/selectTimeRestrictions.tsx, repos/fdbt-site/src/pages/viewTimeRestrictions.tsx, repos/fdbt-site/tests/pages/viewTimeRestrictions.test.tsx
-   Show continue button on select time restriction page. …
=> fix: show continue button on select time restrictions page

repos/fdbt-site/src/design/modules/_components.scss, repos/fdbt-site/src/pages/home.tsx, repos/fdbt-site/src/pages/index.tsx, repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/index.test.tsx.snap, repos/fdbt-site/tests/pages/home.test.tsx, repos/fdbt-site/tests/pages/index.test.tsx
-   Homepage updates for Global settings
-   Check the styling of the home page for global settings
-   Check that the index page navigates to the home page …
=> CFD-303 Homepage updates for Global settings

repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/design/modules/_cards.scss, repos/fdbt-site/src/pages/selectPassengerType.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/src/pages/selectTimeRestrictions.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/src/pages/viewPurchaseMethods.tsx, repos/fdbt-site/src/utils/index.ts, repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/selectPassengerType.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPurchaseMethods.test.tsx.snap
-   Styling for card sizes and layout
-   Check that long/short cards are displayed correctly at all points in the site where they are displayed
- Time Restrictions
- Passenger Types
- Purchase Methods …
=> feat: CFD-393 Styling for card sizes and layout

repos/fdbt-site/src/utils/nextLogger.ts
-   fix next logging webpack issue
-   Deploys properly to test
-   [X] chore - Other changes that don't modify src or test files …
=> chore: CFD-365 fix next logging webpack issue

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/src/pages/api/login.ts, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx
-   To allow the UI tests to use the new purchase methods page.
-   Run UI tests.
-   [x] test - Adding missing tests or correcting existing tests …
=> test: Fixed purchase methods page

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx
-   Fix off by one error in purchase methods UI tests
-   Let UI tests run
-   [ …
=> test: CFD-346 purchase methods UI tests

repos/fdbt-netex-output/package-lock.json
-   fix audit issue with tar
-   Audit should pass
-   [X] build - Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm) …
=> build: fix audit issue with tar

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
-   This will fix the UI tests on fdbt-site.
-   [ ] chore - Other changes that don't modify src or test …
=> test: fix site ui tests

repos/fdbt-site/cypress_tests/cypress/integration/carnet/scheme.ts, repos/fdbt-site/cypress_tests/cypress/integration/multiOperator.ts, repos/fdbt-site/cypress_tests/cypress/integration/scheme.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
-   Improve UI tests on fdbt-site
-   [ …
=> test: improve the ui tests on fdbt-site

repos/fdbt-site/src/constants/index.ts, repos/fdbt-site/src/layout/SubNavigation.tsx, repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/pages/salesOfferPackages.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/src/pages/selectSalesOfferPackage.tsx, repos/fdbt-site/tests/pages/salesOfferPackages.test.tsx
-   To fix visual bugs found around purchase methods.
-   Use ticket as guide to ensure bugs are fixed.
-   [ ] chore - Other changes that don't …
=> fix: Fixed visual bugs for purchase methods

repos/fdbt-site/src/pages/fareConfirmation.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareConfirmation.test.tsx.snap
-   To correct the redirect location in the fare confirmation page, and to alter the wording on the time restrictions.
-   Run locally and retest issues found in ticket. …
=> fix: Altered link wording and redirect location according to if GS enabled

fdbt-aws/sql/l.fareDayEnd.sql, fdbt-aws/sql/z.createUsers.sql, repos/fdbt-site/src/components/CsrfForm.tsx, repos/fdbt-site/src/components/InfoPopup.tsx, repos/fdbt-site/src/components/SettingOverview.tsx, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/design/modules/_popups.scss, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/layout/SubNavigation.tsx, repos/fdbt-site/src/pages/api/manageFareDayEnd.ts, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/src/pages/manageFareDayEnd.tsx, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/components/InfoPopup.test.tsx, repos/fdbt-site/tests/components/__snapshots__/InfoPopup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap, repos/fdbt-site/tests/pages/api/manageFareDayEnd.test.ts, repos/fdbt-site/tests/pages/globalSettings.test.tsx, repos/fdbt-site/tests/pages/manageFareDayEnd.test.tsx
-   Fare day end global settings
-   Check that you can create / edit the Fare Day End setting in Global settings
-   Check the additional GS pages show the Fare Day End info correctly
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: …
=> feat: CFD-298 Fare day end global settings

repos/fdbt-site/cypress_tests/cypress/support/passengerTypes.ts
-   fix ui test on passenger types
-   [ …
=> test: get ui test on passenger types passing

repos/fdbt-site/server/index.ts
-   Suppress invalid URL paths we are getting from bots
-   N/A
-   [X] chore - Other changes that don't modify src or test files …
=> chore: Suppress invalid URL paths we are getting from bots

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts
-   Fix fare day UI journey selection
-   UI Tests …
=> test: Fix fare day UI journey selection

repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/constants/featureFlag.ts, repos/fdbt-site/src/pages/api/deletePassenger.ts, repos/fdbt-site/src/pages/api/deletePurchaseMethod.ts, repos/fdbt-site/src/pages/api/deleteTimeRestriction.ts, repos/fdbt-site/tests/components/GlobalSettingsViewPage.test.tsx, repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap
-   hide delete option on global settings behind a feature flag
-   [ ] chore - Other changes that don't …
=> feat: cfd-422 hide delete option behind a new feature flag

repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/constants/featureFlag.ts, repos/fdbt-site/src/pages/api/deletePassenger.ts, repos/fdbt-site/src/pages/api/deletePurchaseMethod.ts, repos/fdbt-site/src/pages/api/deleteTimeRestriction.ts, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/components/GlobalSettingsViewPage.test.tsx, repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap
-   To make a space smaller on the page.
-   N/A …
=> fix: removed unneeded class

repos/fdbt-site/src/constants/featureFlag.ts, repos/fdbt-site/tests/pages/__snapshots__/salesConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/selectPurchaseMethods.test.tsx.snap, repos/fdbt-site/tests/pages/api/carnetFareType.test.ts, repos/fdbt-site/tests/pages/api/definePassengerType.test.ts, repos/fdbt-site/tests/pages/api/defineTimeRestrictions.test.ts, repos/fdbt-site/tests/pages/api/fareType.test.ts, repos/fdbt-site/tests/pages/api/multipleOperators.test.ts, repos/fdbt-site/tests/pages/api/multipleProducts.test.ts, repos/fdbt-site/tests/pages/api/passengerType.test.ts, repos/fdbt-site/tests/pages/api/pointToPointPeriodProduct.test.ts, repos/fdbt-site/tests/pages/api/selectPassengerType.test.ts, repos/fdbt-site/tests/pages/api/selectSalesOfferPackage.test.ts, repos/fdbt-site/tests/pages/salesConfirmation.test.tsx
-   Enable feature flag for global settings
-   Test on preprod/prod
-   [ ] …
=> feat: CFD-379 Enable feature flag for global settings

repos/fdbt-site/src/pages/api/manageOperatorDetails.ts, repos/fdbt-site/src/pages/manageOperatorDetails.tsx, repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap, repos/fdbt-site/tests/pages/api/manageOperatorDetails.test.ts, repos/fdbt-site/tests/pages/manageOperatorDetails.test.tsx
-   Addresses code and validation issues for operator details change
-   Test that all fields are now mandatory except for contact number, email and url (but at least one of these three is required)
- Test that inputs of >200 chars are not allowed
-   [ ] ci - Changes …
=> fix: edit operator details issues

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/services.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/services.test.tsx.snap, repos/fdbt-site/tests/pages/products/pointToPointProducts.test.tsx, repos/fdbt-site/tests/pages/products/services.test.tsx
-   To allow users to view the products they have assigned to their services for P2P products.
-   Run locally and create products against BODS services. …
=> feat: point to point products against services

repos/fdbt-site/cypress_tests/cypress/support/steps.ts
-   Fixes UI tests on `develop`
-   Check Circle CI and see if UI tests pass.
- …
=> tests: fixing UI tests

repos/fdbt-site/src/pages/api/selectSalesOfferPackage.ts, repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/tests/pages/__snapshots__/selectPurchaseMethods.test.tsx.snap, repos/fdbt-site/tests/pages/api/selectSalesOfferPackage.test.ts
-   To stop users seeing the error when they press the back button on the thankyou page, and also fix the issues around the purchase methods page.
-   Complete the journey for a single, a period ticket (multiple products), and carnet, and ensure the purchase methods page works in all situations (input incorrect prices, dont select a purchase methods, multiple purchase methods etc). …
=> fix: purchase methods bug and back button issue

.circleci/config.yml, repos/exporter/lib/exporter-stack.ts, repos/exporter/package-lock.json, repos/exporter/package.json
-   Add alarms to export lambda
-   N/A
-   [X] chore - Other changes that don't modify src or test files
-   [ ] revert - Reverts a previous …
=> chore: Add alarms to export lambda

repos/exporter/lib/bastionTerminator.ts, repos/exporter/lib/exporter-stack.ts, repos/exporter/package-lock.json, repos/exporter/package.json
-   Restart bastions weekly
-   N/A
-   [X] chore - Other changes that don't modify src or test files
- …
=> chore: CFD-388 Restart bastions weekly

repos/fdbt-site/cypress_tests/cypress/integration/carnet/flatFare.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/index.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx
-   Fix UI tests
-   Check CircleCI
- …
=> test: fixing UI tests

repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/src/pages/products/otherProducts.tsx
-   To ensure products are correctly added to the products table.
-   Run locally and attempt to create some 'other products'.
-   [ ] chore - …
=> fix: Fixed products table bugs

.circleci/config.yml, repos/fdbt-netex-output/package-lock.json, repos/fdbt-netex-output/package.json, repos/fdbt-netex-output/src/netex-validator/package-lock.json, repos/fdbt-reference-data-service/src/retrievers/package-lock.json, repos/fdbt-reference-data-service/src/uploaders/package-lock.json, repos/fdbt-site/cypress_tests/package-lock.json, repos/fdbt-site/package-lock.json, repos/fdbt-site/package.json
-   resolve audit issues
-   N/A
-   [X] build - Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
-   [ …
=> build: resolve audit issues

repos/fdbt-site/src/data/auroradb.ts
-   Fixes linting errors
-   [x] chore - Other changes that don't modify src or test files
-   [ ] revert …
=> fix linting errors on site

repos/fdbt-site/src/components/InformationSummary.tsx, repos/fdbt-site/src/pages/api/fareType.ts, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/src/pages/manageFareDayEnd.tsx, repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/src/pages/managePassengerTypes.tsx, repos/fdbt-site/src/pages/managePurchaseMethod.tsx, repos/fdbt-site/src/pages/manageTimeRestriction.tsx, repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/managePurchaseMethod.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageTimeRestriction.test.tsx.snap, repos/fdbt-site/tests/pages/api/fareType.test.ts, repos/fdbt-site/tests/pages/fareType.test.tsx, repos/fdbt-site/tests/pages/managePassengerTypes.test.tsx, repos/fdbt-site/tests/pages/managePurchaseMethod.test.tsx, repos/fdbt-site/tests/pages/manageTimeRestriction.test.tsx
-   To inform users that when they edit a passenger type or similar, it will affect their fares information.
-   Run locally and use operator settings. …
=> feat: information banner on edit pages

repos/fdbt-site/src/pages/api/salesConfirmation.ts
-   To ensure created files have different names always.
-  n/a …
=> fix: Added extra character to uuid

fdbt-aws/README.md, fdbt-aws/functions/custom_email_trigger.py, fdbt-aws/template/emailTemplate.html, fdbt-dev/README.md, repos/exporter/lib/database.ts, repos/fdbt-netex-output/README.md, repos/fdbt-netex-output/src/netex-emailer/template/emailTemplate.ts, repos/fdbt-reference-data-service/README.md
-   Rename the service
-   Get an email and check it refers to the Create Fares Data service
-   [ ] chore - Other changes that don't modify src or …
=> feat: Rename service

repos/fdbt-site/src/design/modules/_helpers.scss, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap
-   Fix table styling when we have long entries
-   Text should now wrap on long entries of description and time restriction. …
=> feat: cfd-455 fix table styling on long entries

repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
-   Re-order fields 
-   Open same product details pages on develop
-   [ ] …
=> fix: cfd-460-view-period-product-details

fdbt-dev/data/matchingData/return.json, fdbt-dev/data/netexData/return.xml, repos/fdbt-site/package-lock.json, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/interfaces/typeGuards.ts, repos/fdbt-site/src/pages/api/productDateInformation.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/productDateInformation.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/products/services.tsx, repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-site/tests/pages/__snapshots__/productDateInformation.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/salesConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/api/productDateInformation.test.ts, repos/fdbt-site/tests/pages/api/salesConfirmation.test.ts, repos/fdbt-site/tests/pages/salesConfirmation.test.tsx, shared/matchingJsonTypes.ts
-   Remove requirement for end date
-   For a p2p and non-p2p ticket, create one with and without an end date
- Check that netex gets created and validated with/without an end date as expected
- Check that the fares are displayed correctly in My fares
-   [ ] ci - …
=> feat: CFD-385 Remove requirement for end date

repos/fdbt-netex-output/package.json, repos/fdbt-site/src/components/BackButton.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
-   Adds back buttons to the dead end my fares pages
-   Test the back buttons navigate backwards as expected
-   [ ] chore - Other changes that …
=> feat: cfd-506 add back buttons

repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
- Create a page that displays all key elements of a scheme fare.
-   Pull branch locally and delete ` && (ticketType === 'geoZone' || dataFormat !== 'tnds')` from line 640 in _repos/fdbt-site/src/utils/apiUtils/userData.ts_
- Create the following products using the **scheme** login:
1. Period -> Set of Services
2. Period -> Geozone
3. Carnet Period -> Set of Services
4. Carnet Period -> Geozone
5. Flat Fare
6. Carnet Flatfare 
- Check that the product details page shows all the correct information (Check Jira for refrence)
-   [ ] refactor - A code change that neither fixes …
=> feat: CFD-462 view scheme product details

repos/fdbt-site/src/pages/home.tsx, repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap, repos/fdbt-site/tests/pages/home.test.tsx
-   Altered duplicated id and added new snapshot test
-   n/a …
=> fix: Altered id and added new snapshot test

repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
-   Ensuring exceptions aren't thrown when directional descriptions are missing from TXC.
-   Reference data import should not error around directional descriptions missing.
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, …
=> feat: Reworked logic around extracting txc data

repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/productCreated.tsx, repos/fdbt-site/src/pages/thankyou.tsx, repos/fdbt-site/tests/pages/__snapshots__/productCreated.test.tsx.snap, repos/fdbt-site/tests/pages/productCreated.test.tsx
-   Creation of a new page to go alongside the thankyou page, but specifically for BODS data users.
-   Run locally and use BODS data to create a ticket. …
=> feat: Added new last page behind export feature flag

fdbt-aws/cloudformation/service/eu-west-2/iam.yml, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/exports.ts, repos/fdbt-site/src/pages/products/exports.tsx
-   Fixing the problems on test with the exporter.
-   Exports page should work. …
=> fix: exporter issues on test

repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/pointToPointProducts.test.tsx
-   Needs attention products needed an error summary at the top of the page, this PR adds that.
-   Create a point to point product, change the needs attention to true in the code (line 190 in tsx file), and ensure the warning appears.
-   [ ] ci - Changes to our CI …
=> bug: Added missing error summary

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/exports.ts, repos/fdbt-site/src/pages/products/services.tsx
-   Fix bulk export. The issue was caused by the date format being wrong.
-   Attempt a bulk export …
=> feat: cfd-445 - fix dates format

repos/fdbt-netex-output/serverless.yml
-   Add a lifecycle rule to objects in the `fdbt-netex-data` bucket.
-   Check on AWS Console to see if the lifecycle policy exists and that it is for 3 months. …
=> feat: cfd-523 - add a lifecycle policty to s3 bucket

fdbt-aws/cloudformation/service/eu-west-2/fargate.yml, fdbt-aws/cloudformation/service/eu-west-2/vpc.yml
Remove deployment of no longer required Prototype application, reducing
costs and security footprint
Resources removed from Test AWS account
-   [x] refactor - A code change that neither fixes a bug nor adds a feature
-   [ …
=> feat: cfd-534 removal of prototype application

repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/design/modules/_components.scss, repos/fdbt-site/src/design/modules/_helpers.scss, repos/fdbt-site/src/pages/api/deleteProduct.ts, repos/fdbt-site/src/pages/products/otherProducts.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/otherProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap, repos/fdbt-site/tests/pages/products/otherProducts.test.tsx, repos/fdbt-site/tests/pages/products/pointToPointProducts.test.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx, shared/dbTypes.ts
-   Delete products in my fares
-   Check that you can delete products for both P2P and Other Products in My Fares …
=> feat: CFD-509 Delete products

repos/fdbt-site/src/pages/manageFareDayEnd.tsx, repos/fdbt-site/src/pages/manageOperatorDetails.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/manageFareDayEnd.test.tsx, repos/fdbt-site/tests/pages/manageOperatorDetails.test.tsx, repos/fdbt-site/tests/pages/viewPassengerTypes.test.tsx
-   These changes make the navigation consistent.
-   Check to see if the export tab is shown on the various pages. (previously, it would show on some pages and be hidden on other pages).
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: …
=> add consistency to navigation

repos/fdbt-site/cypress_tests/cypress/integration/carnet/scheme.ts, repos/fdbt-site/cypress_tests/cypress/integration/scheme.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts
fix ui tests for bods and tnds data
run ui tests …
=> Fix/cfd 532 fix UI tests

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/exports.ts
-   Add the replace internal noc function call to the db calls relating to bulk export and also handle products not related to services
-   Attempt a bulk export …
=> feat: cfd-445 - fix bulk export ... again

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/data/s3.ts
-   On non-reference data, IWBusCo should not be swapped.
-   Attempt a bulk export
-   [ ] chore - Other changes that don't modify src or test …
=> feat: cfd-445 - Remove the swapping of IWBusCo on non-reference data

.circleci/config.yml, repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
-   Fixes the errors seen in ref data import due to get being called on None
-   I've tested that the ref data import works without errors on test …
=> fix: cfd 533 ref data import error

fdbt-aws/cloudformation/service/eu-west-2/rds.yml, repos/exporter/lib/database.ts, repos/exporter/lib/exporter-stack.ts, repos/fdbt-netex-output/src/data/auroradb.ts
-   Exporter alerts for DB connections …
=> fix: Exporter alerts for DB connections

repos/fdbt-site/src/components/InfoPopup.tsx, repos/fdbt-site/src/components/LoadingSpinner.tsx, repos/fdbt-site/src/design/main.scss, repos/fdbt-site/src/design/modules/_components.scss, repos/fdbt-site/src/design/modules/_spinner.scss, repos/fdbt-site/src/pages/api/exports.ts, repos/fdbt-site/src/pages/api/getExportProgress.ts, repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/tests/components/LoadingSpinner.test.tsx, repos/fdbt-site/tests/components/__snapshots__/InfoPopup.test.tsx.snap, repos/fdbt-site/tests/components/__snapshots__/LoadingSpinner.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/exports.test.tsx.snap
-   To improve multiple areas of the exports page.
-   Run locally and manually pass in data or add sleeps to see features. …
=> feat: export improvements 

fdbt-aws/cloudformation/service/eu-west-2/iam.yml, repos/exporter/lib/exporter-stack.ts, repos/exporter/lib/zipperHandler.ts, repos/exporter/package-lock.json, repos/exporter/package.json, repos/fdbt-site/package-lock.json, repos/fdbt-site/package.json, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/getExportProgress.ts, repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/src/utils/apiUtils/export.ts, shared/integrationTypes.ts
-   Zip at the end of an export using a lambda
-   Export testing
-   [ ] revert …
=> feat: CFD-539 Zip Lambda

repos/exporter/lib/exporter-stack.ts, repos/fdbt-netex-output/serverless.yml
-   Speed up exporter and zipper
-   [X] perf - A code change that improves performance
-   [ …
=> perf: Speed up exporter and zipper

fdbt-aws/cloudformation/service/eu-west-2/fargate.yml
-   Give more CPU to the site
-   [X] perf - A code change that improves performance
-   [ ] …
=> perf: CFD-549 Performance issues on site

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
-   Fix bug with loading product details page
-   Login as TBTN and navigate to the following page
-   /products/productDetails?productId=6222&serviceId=2376 …
=> fix: CFD-542 Fix bug with loading product details page

repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx, repos/fdbt-site/src/pages/fareConfirmation.tsx, repos/fdbt-site/src/pages/productCreated.tsx, repos/fdbt-site/src/pages/products/otherProducts.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/__snapshots__/productCreated.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
-   Make UI changes on MyFares pages
-   Check [ticket](https://infinityworks-dft.atlassian.net/browse/CFD-544) and see that everything has been done. …
=> feat: cfd-544 - make changes to the user interface on my fares pages

fdbt-aws/cloudformation/service/eu-west-2/fargate.yml
-   Horizontally scale the site across environments
-   [X] perf - A code change that improves performance …
=> perf: CFD-550 Horizontally scale the site across environments

repos/fdbt-site/src/pages/products/productDetails.tsx
-   Add carnet on carnet products on products details page
-   Create a carnet product and check it on the products details page. It should have `(carnet)` after its type. …
=> feat: cfd-544 - add carnet on carnet products on products details page

repos/fdbt-site/src/constants/featureFlag.ts, repos/fdbt-site/tests/pages/products/otherProducts.test.tsx
-   Enable Export and View My Fares
-   Good test to be done on Pre-Prod
-   [ ] …
=> feat: CFD-562 Enable Export and View My Fares

repos/fdbt-site/src/pages/fareConfirmation.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/fareConfirmation.test.tsx
-   Error with groups on confirmation page
-   Create a fare with a group
-   [ ] …
=> fix: Error with groups on confirmation page

repos/fdbt-site/src/pages/fareConfirmation.tsx, repos/fdbt-site/tests/pages/__snapshots__/fareConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/fareConfirmation.test.tsx
fix: Error with groups on confirmation page (#335)
=> Preprod fix

repos/fdbt-site/src/pages/salesConfirmation.tsx, repos/fdbt-site/tests/pages/__snapshots__/salesConfirmation.test.tsx.snap
-   Update the wording on the sales confirmation page
-   On `/salesConfirmation` ensure the bottom heading says **Now submit your data to create the product** and that the button is **Accept and submit**. …
=> feat: cfd-551 - update the wording on the sales confirmation page

repos/fdbt-site/cypress_tests/cypress/integration/multiOperator.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/src/pages/multipleOperatorsServiceList.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap, repos/fdbt-site/tests/pages/api/salesConfirmation.test.ts
-   Fix the scheme journey
- As a scheme:  
- Check you can switch between TNDS and BODS data for operators that have both
- Check that no matter what you pick, you are emailed the Netex at the end
- Check that nothing gets to MyFares
- As a normal operator:
- Check that MyFares works
- Check that there is no Multi-Operators option
-   [ ] build - Changes that affect the build …
=> fix: Scheme journey

repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap
-   Updates the needs attention warning on the pointToPointProducts page
-  Assert that the warning displays correctly. …
=> feat: cfd 561 update matchign warning

repos/fdbt-site/cypress_tests/cypress/support/steps.ts
-   Sorts the direction issue seen with single tickets
-   Test the single ticket UI tests can pass for services with 1 and with multiple directions
-   [x] test - Adding missing tests or correcting existing tests …
=> test: fix ui tests single direction

repos/fdbt-site/server/middleware/sessions.ts
This ensures session cookies are always marked as httpOnly and are
marked as secure when not in development, as the local servers do not
run over HTTPS
- Use browser dev tools to ensure cookies are marked as `secure` and `httpOnly`
- Compare between pre-deployment state and post deployment
- Ensure Github CodeQL is happy this code resolves https://github.com/fares-data-build-tool/create-data/security/code-scanning/13?query=ref%3Arefs%2Fheads%2Fdevelop
-   [ ] perf - A code change that improves …
=> Ensuring secure Session Cookie Options are set

repos/fdbt-site/src/components/UserDataUploads.tsx, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/updateFareTriangle.ts, repos/fdbt-site/src/pages/csvUpload.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/utils/apiUtils/fileUpload.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/api/updateFareTriangle.test.ts, repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx, shared/matchingJsonTypes.ts
-   Edit fare triangle prices
-   For points to points, attempt to edit by uploading a new csv (edit existing csv, for example; change fare stage names and add a new fare stage)
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, …
=> feat: cfd-481 - edit fare triangle prices

repos/fdbt-netex-output/src/netex-convertor/handler.test.ts, repos/fdbt-netex-output/src/netex-convertor/handler.ts, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-site/src/interfaces/index.ts
-   When the first stop in the first fare stage matches the last stop in the last fare stage, the said stop is removed.
-   Test with a route that matches above description …
=> fix: cfd-566 fix netex output

repos/fdbt-reference-data-service/src/retrievers/serverless.yml
-   Adds missing variables to lambda
-   Run Txc tnda/bods lambda (both) and ensure they work …
=> fix: cfd-397 - add missing environmental variables to serverless config

repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
-   Fix bug in netex generation
-   Test with FSRV noc on Test Env
-   [ ] revert …
=> fix: cfd-566 - fix bug in netex generation

repos/fdbt-reference-data-service/src/retrievers/serverless.yml
-   Fix lambda permissions
-   Run on preprod to test it out. …
=> fix: cfd-397 - fix permissions

repos/fdbt-site/.dockerignore, repos/fdbt-site/Dockerfile, repos/fdbt-site/cypress_tests/package-lock.json, repos/fdbt-site/cypress_tests/package.json, repos/fdbt-site/fdbt-types/.gitignore, repos/fdbt-site/fdbt-types/README.md, repos/fdbt-site/fdbt-types/dbTypes.js, repos/fdbt-site/fdbt-types/dbTypes.ts, repos/fdbt-site/fdbt-types/integrationTypes.js, repos/fdbt-site/fdbt-types/integrationTypes.ts, repos/fdbt-site/fdbt-types/matchingJsonTypes.js, repos/fdbt-site/fdbt-types/matchingJsonTypes.ts, repos/fdbt-site/fdbt-types/package-lock.json, repos/fdbt-site/fdbt-types/package.json, repos/fdbt-site/fdbt-types/tsconfig.json, repos/fdbt-site/package-lock.json, repos/fdbt-site/package.json
Local scoping of directories in build context doesn't pick up fdbt-types
local package, resulting in next build failing
N/A …
=> fix: cfd-587 temporary fix for docker build

repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
-   Check to see if services exist before attempting to use it
-   Txc Uploader should no longer give the error about Services being missed.
-   [ …
=> feat: cfd-591 - check to see if services exist before attempting to use it

repos/fdbt-site/src/utils/apiUtils/matching.ts
-   change the log level down to a *warning*
-   Check logs in cloud watch when toposort fails. …
=> feat: cfd-593 - change log level down to a warning

repos/fdbt-site/src/pages/api/manageFareDayEnd.ts, repos/fdbt-site/src/pages/api/manageOperatorDetails.ts, repos/fdbt-site/src/pages/api/managePassengerGroup.ts, repos/fdbt-site/src/pages/api/managePassengerTypes.ts, repos/fdbt-site/src/pages/api/managePurchaseMethod.ts, repos/fdbt-site/src/pages/api/manageTimeRestriction.ts, repos/fdbt-site/src/pages/api/productDateInformation.ts, repos/fdbt-site/src/utils/apiUtils/index.ts, repos/fdbt-site/src/utils/apiUtils/validator.ts, repos/fdbt-site/tests/pages/api/apiUtils/validator.test.ts, repos/fdbt-site/tests/pages/api/managePassengerTypes.test.ts
-   Check for invalid characters
-   Test some inputs with invalid characters such as `>` and `"` …
=> feat: cfd-555 - input validation

repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
-   Remove duplicate scheduled stop points
-   Netex generation on NWBT
-   [ ] …
=> feat: cfd-625 - remove duplicates on scheduled stop points

fdbt-aws/cloudformation/service/eu-west-2/vpc.yml
restrict uploader sg egress
Ensure uploader Lambdas still run …
=> fix: cfd-623 restrict uploader sg egress

repos/fdbt-reference-data-service/src/retrievers/csv_retriever/main.py, repos/fdbt-reference-data-service/src/retrievers/requirements.txt, repos/fdbt-reference-data-service/src/retrievers/serverless.yml, repos/fdbt-reference-data-service/src/uploaders/csv_uploader/db_queries.py
-   Handle the new URL and refactor the naptan handler.
-   Run the handler via the AWS Console …
=> feat: cfd-568 - migrate new naptan site

repos/fdbt-reference-data-service/src/retrievers/txc_retriever/main.py, repos/fdbt-reference-data-service/src/uploaders/csv_uploader/db_queries.py, repos/fdbt-reference-data-service/src/uploaders/tests/test_csv_uploader.py
fix: cfd-630 idempotent ref data table creation
Manually trigger Lambdas or wait overnight for scheduled processes …
=> fix: cfd-630 idempotent ref data table creation

fdbt-aws/cloudformation/service/eu-west-2/vpc.yml
fix grafana
visit monitoring site
- …
=> cfd-622 grafana efs fix

.circleci/config.yml
build: cfd-543 check ECR image scan results
Only affects CircleCI builds, not anything deployed to AWS
-   [ ] chore - Other changes that don't …
=> build: cfd-543 check ECR image scan results

.circleci/config.yml
build: cfd-543 fix build step dependencies
Ensure pipeline visualisations in CircleCI are correct …
=> build: cfd-543 fix build step dependencies

repos/fdbt-site/src/constants/featureFlag.ts
feat: cfd-629 enable globalSettingsDeleteEnabled in all environments
Might be worth Steven giving this a once over? …
=> feat: cfd-629 enable globalSettingsDeleteEnabled

repos/fdbt-site/server/middleware/logging.ts
`noc` will be added to logs if available
- Need to create an error state in test
- Should see something like this in CloudWatch
- `{"req":{"url":"/home","method":"GET","httpVersion":"1.1"},"res":{"statusCode":500},"responseTime":368,"noc":"BLAC","level":"info","message":"HTTP GET /home"}`
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: …
=> refactor: cfd-520 add noc to log context

docs/how-to/update-or-change-the-site-error-page.md, repos/fdbt-site/error/outage/index.html, repos/fdbt-site/error/outage/main.css
Service Unavailable page and docs
Check docs as well …
=> build: cfd-637 Service Unavailable page and docs

.github/pull_request_template.md, fdbt-aws/scripts/cfd-bastion-tunnel, repos/fdbt-admin/amplify/backend/auth/fdbtadmin65b519f2/fdbtadmin65b519f2-cloudformation-template.yml, repos/fdbt-reference-data-service/src/retrievers/serverless.yml
Remove unused section from PR template
Make database tunnel script safer and support old and new domain names
Remove old domain reference in Admin deployment template
Enable ref data retrievers in test, which were just manually enabled
n/a
=> build: cfd-633 post dns change rebuild fixes

docs/reference/environment-listing.md, docs/reference/high-level-design.md, fdbt-aws/scripts/cfd-bastion-tunnel, fdbt-aws/template/emailTemplate.html
Remove references to old domain
n/a
=> fix: cfd-644 remove references to old domain

repos/fdbt-netex-output/serverless.yml, repos/fdbt-netex-output/src/netex-emailer/handler.test.ts, repos/fdbt-netex-output/src/netex-emailer/handler.ts
Disabling NetexEmailer SES email sending
Copy file into matching data bucket, but not into either the `<NOC>/exports` or `<NOC>/zips` paths, which get skipped by the sender
=> fix: cfd-647 disabling netexemailer sending

docs/how-to/README.md, docs/how-to/clean-up-ui-test-nocs.md, fdbt-dev/scripts/cleanup_ui_test_nocs.sh
Script to manually clean up UI Test resources
Process in the doc already run in test
=> build: cfd-639 script that will clean up UI test data in test env

repos/fdbt-netex-output/src/netex-emailer/handler.test.ts, repos/fdbt-netex-output/src/netex-emailer/handler.ts, repos/fdbt-site/src/pages/api/feedback.ts, repos/fdbt-site/src/utils/apiUtils/feedbackEmailer.ts, repos/fdbt-site/src/utils/apiUtils/index.ts, repos/fdbt-site/tests/pages/api/feedback.test.ts
improve logging of email sending, also cc in feedback to users so they know it's been sent
- Use feedback form
- Ensure logs now have redacted users in to emails
=> fix: cfd-650 improve logging of email sending

.github/workflows/fdbt-netex-output.yml, .github/workflows/fdbt-netex-output_prod_deployment.yml
=> changing the github path

.github/workflows/fdbt-netex-output.yml, .github/workflows/fdbt-netex-output_prod_deployment.yml
=> update serleverless to 3.22.0

.github/workflows/exporter_all_branches.yml, .github/workflows/exporter_preprod_deployment.yml, .github/workflows/exporter_test_deployment.yml, .github/workflows/fdbt-netex-output.yml, .github/workflows/fdbt-netex-output_all_branches.yml, .github/workflows/fdbt-netex-output_preprod_deployment.yml, .github/workflows/fdbt-netex-output_test_deployment.yml, .github/workflows/fdbt-reference-data-service_all_branches.yml, .github/workflows/fdbt-reference-data-service_preprod_deployment.yml, .github/workflows/fdbt-reference-data-service_test_deployment.yml, .github/workflows/fdbt-site_preprod_deployment.yml, .github/workflows/fdbt-site_prod_deployment.yml, .github/workflows/fdbt-site_test_deployment.yml
=> Migrate circle ci pipelines

.github/workflows/fdbt-site_prod_deployment.yml, .github/workflows/fdbt-site_test_deployment.yml
=> updat e var names

repos/fdbt-admin/.eslintignore, repos/fdbt-admin/amplify/backend/backend-config.json, repos/fdbt-admin/package-lock.json, repos/fdbt-admin/package.json, repos/fdbt-admin/src/App.tsx, repos/fdbt-admin/src/pages/AddUser.tsx, repos/fdbt-admin/src/pages/ListUsers.tsx, repos/fdbt-admin/src/pages/ResendInvite.tsx, repos/fdbt-admin/src/utils/cognito.ts
Admin panel feature to resend an invite to a user who is awaiting registration.
amplify serve, and resend an invite.
=> feat: Added functionality for resending invites

repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap, repos/fdbt-site/tests/pages/managePassengerGroup.test.tsx
To test the automatic deployment of develop to test.
=> Testing deployment trigger

.github/workflows/fdbt-site_test_deployment.yml
=> adding run ui tests

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/src/components/DateSelector.tsx, repos/fdbt-site/src/pages/api/productDateInformation.ts, repos/fdbt-site/src/pages/productDateInformation.tsx, repos/fdbt-site/tests/components/DateSelector.test.tsx, repos/fdbt-site/tests/components/__snapshots__/DateSelector.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/productDateInformation.test.tsx.snap, repos/fdbt-site/tests/pages/api/productDateInformation.test.ts, repos/fdbt-site/tests/pages/productDateInformation.test.tsx
To enforce the user to add a start date when creating or editing a product.
Run locally and attempt to not add a start date.
=> feat: changed product date start date to mandatory

.github/workflows/fdbt-site_preprod_deployment.yml, .github/workflows/fdbt-site_prod_deployment.yml
=> fix prepord developemnt

.github/workflows/fdbt-site_preprod_deployment.yml, .github/workflows/fdbt-site_prod_deployment.yml
=> fix prepord developemnt (#511)

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/copyProduct.ts, repos/fdbt-site/src/pages/products/otherProducts.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-site/tests/pages/api/copyProduct.test.ts, repos/fdbt-site/tests/pages/products/__snapshots__/otherProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
To give users the ability to duplicate a product, so that they can quickly create new tickets if they are very similar.
Create a product and then hit copy in the product list inside My Fares.
=> feat: duplicate products

.github/workflows/fdbt-netex-output_preprod_deployment.yml, .github/workflows/fdbt-netex-output_prod_deployment.yml, .github/workflows/fdbt-netex-output_test_deployment.yml
=> fix: Altered ubuntu runner version

repos/fdbt-site/error/error/index.html, repos/fdbt-site/error/outage/index.html, repos/fdbt-site/src/layout/Footer.tsx, repos/fdbt-site/src/pages/accessibility.tsx, repos/fdbt-site/tests/layout/__snapshots__/Footer.test.tsx.snap
TFN is referenced in the footer, needs removing.
=> fix: remove TFN reference

repos/fdbt-site/src/pages/api/returnValidity.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/api/returnValidity.test.ts, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
Feature to allow the users to edit the return validity on a return ticket.
Create a return product and edit the return validity.
=> feat: edit return validity

repos/fdbt-site/cypress_tests/cypress/integration/school.ts
Disabling UI test for Academic/school ticket
=> disble school test in UI

repos/fdbt-site/cypress_tests/cypress/integration/school.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/returnService.ts, repos/fdbt-site/src/pages/outboundMatching.tsx, repos/fdbt-site/src/utils/apiUtils/matching.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/api/returnService.test.ts
Added changes for the return service to use in outbound matching
Select a return ticket which is circular and will ask for the new service to be selected for outbound and for inbound earlier service will be used.
=> Added changes for the return service to use in outbound matching

repos/fdbt-site/src/pages/multipleProducts.tsx
Removing Terms from Carnet drop menu
locally
=> Remove terms from carnet drop menu

fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/carnetSingle.xml, fdbt-dev/data/netexData/flatFare.xml, fdbt-dev/data/netexData/flatFareGeoZone.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeOperatorFlatFare.xml, fdbt-dev/data/netexData/single.xml, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts
Added the tariffbasis and remove validity conditions
Export the netex and validity conditions is removed and for all flat products, the tariffbasis is flat instead of zone.
=> feat: Added the tariffbasis and remove validity conditions

fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/flatFare.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, fdbt-dev/data/netexData/hybridPeriod.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml, fdbt-dev/data/netexData/schemeOperatorFlatFare.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
Some lines have different dates but the same service code and data. This PR removes the duplicate data for each service code as explained in [CFDS-52](https://deliverybackbone.ema.kpmg.com/pdstudio86/browse/CFDS-52)
Use test data from DB and run tests
=> Feature CFDS-52 - De-duplicate Lines

repos/fdbt-site/cypress_tests/cypress/integration/school.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
Enabling UI test for Academic ticket
test using cypress
=> update school UI test

fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/flatFare.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml, fdbt-dev/data/netexData/schemeOperatorFlatFare.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
Fixing line ref issue mentioned in cloud watch console
Assuming the error occurred in https://github.com/fares-data-build-tool/create-data/pull/551/files
make generate-validate-all
npm run test
npm run lint
=> Fix CFDS-55 - Fixed line ref issue

repos/fdbt-site/cypress_tests/cypress.config.ts
enable type script tests on cypress.config.ts file 
npm run test
=> fix: remove ignored lines comments

fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/carnetReturn.xml, fdbt-dev/data/netexData/carnetSingle.xml, fdbt-dev/data/netexData/flatFare.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, fdbt-dev/data/netexData/hybridPeriod.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/periodPointToPoint.xml, fdbt-dev/data/netexData/return.xml, fdbt-dev/data/netexData/returnCircular.xml, fdbt-dev/data/netexData/returnCircularGroup.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml, fdbt-dev/data/netexData/schemeOperatorFlatFare.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, fdbt-dev/data/netexData/single.xml, fdbt-dev/data/netexData/singleGroup.xml, fdbt-dev/data/netexData/singleGroupMultipleAdults.xml, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
Updating line id from op:${service.lineName}#${service.serviceCode} to just lineId
Check XML to make sure **no** line ids are in this format op:${service.lineName}#${service.serviceCode}
=> feat: CFDS-44 - Line references

repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/tests/pages/fareType.test.tsx
To turn on multi operator for test env only.
Locally it works, needs checking on test environment.
=> fix: Moving env checks to server side props

repos/fdbt-site/src/data/auroradb.ts
To add additional logging to figure out which atco's are missing.
N/a - to be done on test env.
=> chore: Added extra logging for missing atcos

repos/fdbt-types/.prettierrc.cjs, repos/fdbt-types/matchingJsonTypes.ts
To ensure we are all linting the types repo with the same rules.
Format document in one of the files inside the types repo.
=> fix: Added linting rules to types repo

fdbt-dev/data/matchingData/single.json, fdbt-dev/data/matchingData/singleGroup.json, fdbt-dev/data/matchingData/singleGroupMultipleAdults.json, repos/fdbt-netex-output/src/data/s3.ts, repos/fdbt-netex-output/src/netex-convertor/handler.test.ts, repos/fdbt-netex-output/src/netex-convertor/handler.ts
There was a bug in creating the names for netex files, where it wasn't checking for them properly. We have also added lineName and direction for point to point tickets, to make it less likely there are duplicates.
Needs running on test environment to do a proper export.
=> fix: Fixed netex file name creation

fdbt-aws/cloudformation/service/eu-west-2/iam.yml, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/src/constants/index.ts, repos/fdbt-site/src/pages/api/deleteProduct.ts
Changing search term in UI tests so it uses operators with BODS data. Also, updating deleting products.
UI tests to pass in pipeline.
=> fix: Fix for UI tests

repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx, repos/fdbt-site/src/layout/SubNavigation.tsx, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/src/pages/manageFareDayEnd.tsx, repos/fdbt-site/src/pages/manageOperatorDetails.tsx, repos/fdbt-site/src/pages/viewOperatorGroups.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/src/pages/viewPurchaseMethods.tsx, repos/fdbt-site/src/pages/viewTimeRestrictions.tsx, repos/fdbt-site/tests/components/GlobalSettingsViewPage.test.tsx, repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap, repos/fdbt-site/tests/pages/globalSettings.test.tsx
We need to ensure Global Settings operator groups is not enabled in prod, because it is only half finished.
Check operator groups are visible on test, but not on preprod or prod.
=> fix: Changed GS operator groups so it is only enabled on test

fdbt-aws/cloudformation/service/eu-west-2/iam.yml, repos/fdbt-site/src/constants/index.ts, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/cancelExport.ts, repos/fdbt-site/src/pages/products/exports.tsx
This feature gives users the ability to cancel exports if they suspect they have failed for any reason, so that they can delete the problem product and try again.
Use BLAC on test env and export, which will likely cause it to freeze, and then cancel the export.
=> feat: Cancel export button

.github/workflows/fdbt-site_test_deployment.yml, fdbt-aws/cloudformation/service/eu-west-2/iam.yml, repos/fdbt-site/package.json, repos/fdbt-site/src/constants/index.ts, repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/cancelExport.ts, repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/src/utils/index.ts, repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewOperatorGroups.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPurchaseMethods.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewTimeRestrictions.test.tsx.snap, repos/fdbt-site/tests/pages/api/reuseOperatorGroup.test.ts, repos/fdbt-site/tests/pages/api/saveOperatorGroup.test.ts, repos/fdbt-site/tests/pages/manageFareDayEnd.test.tsx, repos/fdbt-site/tests/pages/manageOperatorDetails.test.tsx, repos/fdbt-site/tests/pages/viewOperatorGroups.test.tsx, repos/fdbt-site/tests/pages/viewPassengerTypes.test.tsx, repos/fdbt-site/tests/pages/viewPurchaseMethods.test.tsx, repos/fdbt-site/tests/pages/viewTimeRestrictions.test.tsx, repos/fdbt-site/tests/utils/index.test.ts
To allow users to cancel exports that have frozen.
Cancel an export that has frozen on test env (do not cancel while in progress).
=> feat: cancel exports button

.github/workflows/fdbt-site_test_deployment.yml
=> adding a ecs service stability flag to enable ui tests to work

.github/workflows/fdbt-site_test_deployment.yml
=> Adding service stability

repos/fdbt-site/src/pages/api/getExportProgress.ts, repos/fdbt-site/src/pages/products/exports.tsx
Exports have broken with the addition of the hour-check. This PR makes sure the code only runs if an export has happened.
Export on test env.
=> fix: cancel exports fix

repos/fdbt-site/src/data/s3.ts, repos/fdbt-site/src/pages/api/cancelExport.ts, repos/fdbt-site/src/pages/api/getExportProgress.ts, repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/tests/pages/products/exports.test.tsx
Removed logic around checking time of export, and also only enabling cancel exports for dev or test environment.
Ensure cancel export button still works as expected.
=> fix: Reverted changes for time of export 

repos/fdbt-site/tests/pages/__snapshots__/viewOperatorGroups.test.tsx.snap, repos/fdbt-site/tests/pages/viewOperatorGroups.test.tsx
Fixing the operator in operator group for multi operator ticket
Create the multi operator ticket
=> Fixed the operator group

repos/fdbt-site/src/pages/products/selectExports.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/selectExports.test.tsx.snap
Adding missing service title that was missing from select exports page.
n/a
=> fix: Added service title that was missing

repos/fdbt-site/cypress_tests/cypress/support/e2e.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/multipleOperatorsServiceList.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
Complete the UI test for the multi operator ticket as per the new flow of operator groups.
Execute/Run the UI test for the multi operator ticket journey.
=> feat: UI test - Multioperator ticket

repos/fdbt-site/cypress_tests/cypress.config.ts, repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/products/services.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/services.test.tsx.snap
When the user edits a point to point ticket, they can now edit a multitude of things in the product. We need a UI test for each distinct edit feature.
edit product name
edit passenger type
edit time restriction
edit fare triangle (may already have this?)
edit purchase methods
edit start date
edit end date
Run cypress tests for myFares.cy.ts and they should all pass
=> feat: UI Test - Edit point to point ticket

repos/fdbt-site/cypress_tests/cypress/e2e/globalSettings/multiOperatorGroups.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/e2e.ts, repos/fdbt-site/cypress_tests/cypress/support/multiOperatorGroups.ts, repos/fdbt-site/src/components/OperatorGroupCard.tsx
Adding a journey for add a multi operator group as it was missing.
Run multiOperatorGroups.cy.ts all tests should pass
=> feat: UI Test - Add a MultiOperator Group

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
Fix the UI test for multi operator to select the operator group only for UI test
Fix the assertion issue
Run the UI test for multioperator and myfares
=> Fixing the UI test

repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
A UI test is needed for changing a multiOperator geoZone product's group from one operator group, to another operator group.
Run the myFares.cy.ts all tests should pass
=> feat: UI Test - Edit multiOp geoZone group

fdbt-dev/sql/operatorGroup.sql, fdbt-dev/sql/passengerTypes.sql, fdbt-dev/sql/salesOfferPackage.sql
Creating the operator settings for the development environment
Create the local environment and run it using `make run`
=> feat: Adding the operator settings for operator in dev environment

repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
Cleaning up some of the cypress code.
UI tests should still pass.
=> refactor: Refactoring UI tests

repos/fdbt-site/cypress_tests/cypress/support/steps.ts
To fix breaking UI test in my fares.
n/a
=> test: Changed expected text code

.gitignore, .husky/pre-commit, lerna.json, package-lock.json, package.json, repos/fdbt-admin/package.json, repos/fdbt-netex-output/package.json, repos/fdbt-site/package.json
The precommit hooks (the husky script which runs automatically when you run a commit locally) currently fails. 
try a commit in the different folders: netex, admin and site then see if lerna notices the changes
You may need to install lerna globally `npm install lerna -g`
=> feature: Fix precommit hooks

repos/fdbt-site/src/pages/api/periodValidity.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/api/periodValidity.test.ts, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
Add the edit functionality for the products page (other products page)
Edit the product validity of a product listed in "otherProducts" page.
=> Adding the edit functionality for product validity

repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/api/editPeriodDuration.ts, repos/fdbt-site/src/pages/editPeriodDuration.tsx, repos/fdbt-site/tests/pages/__snapshots__/editPeriodDuration.test.tsx.snap, repos/fdbt-site/tests/pages/api/editPeriodDuration.test.ts
UI test to edit the product period duration in Cypress test
Run myFares.cy tests all should pass
=> feat: UI Test for edit period duration

repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/interfaces/matchingJsonTypes.ts, repos/fdbt-site/src/interfaces/typeGuards.ts, repos/fdbt-site/src/pages/api/capValidity.ts, repos/fdbt-site/src/pages/api/createCaps.ts, repos/fdbt-site/src/pages/selectCapValidity.tsx, repos/fdbt-site/src/utils/globalSettings.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/globalSettingsCapValidity.test.tsx.snap, repos/fdbt-site/tests/pages/api/capValidity.test.ts, repos/fdbt-site/tests/pages/globalSettingsCapValidity.test.tsx, repos/fdbt-site/tests/testData/mockData.ts
We need a page similar to selectPeriodValidity in which we ask the user when their cap expires. This page will come immediately after /createCaps .
Follow cap journey until this page
=> feat: When does cap expire page

repos/fdbt-site/cypress_tests/cypress/support/steps.ts
UI tests were failing on cypress
Run the myFares ui tests all should pass
=> fix: Fix UI tests

repos/fdbt-site/src/pages/selectPassengerType.tsx
Fixing passenger type defaults
Edit a passenger type
=> fix: Passenger type defaults

repos/fdbt-site/src/interfaces/matchingJsonTypes.ts, repos/fdbt-site/src/pages/api/returnService.ts, repos/fdbt-site/tests/pages/api/returnService.test.ts, repos/fdbt-site/tests/testData/mockData.ts
The type was incorrect for the additionalService that can be on Returns.
n/a
=> refactor: Fixed type issue and altered tests

repos/fdbt-reference-data-service/src/retrievers/serverless.yml, repos/fdbt-reference-data-service/src/retrievers/txc_retriever/main.py
Turning back on the trigger for the TNDS retriever lambda.
n/a
=> feat: Added trigger back to serverless file for TNDS lambda

repos/fdbt-site/src/components/TapPricingRow.tsx, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/interfaces/typeGuards.ts, repos/fdbt-site/src/pages/api/multiTapsPricing.ts, repos/fdbt-site/src/pages/api/typeOfCap.ts, repos/fdbt-site/src/pages/multiTapsPricing.tsx, repos/fdbt-site/src/utils/apiUtils/validator.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/components/TapPricingRow.test.tsx, repos/fdbt-site/tests/components/__snapshots__/TapPricingRow.test.tsx.snap, repos/fdbt-site/tests/pages/api/multiTapsPricing.test.ts
Added the page for the price by taps of capped product journey
Create a capped product and select the Taps by price option to create price by number of taps.
=> feat: Added the price by taps for capped products

fdbt-aws/sql/h.salesOfferPackage.sql, fdbt-dev/sql/salesOfferPackage.sql, repos/fdbt-site/src/pages/selectTimeRestrictions.tsx
We need to edit the purchase methods DB table to have a new column 'isCapped'
Check if it is there locally and code review
=> feat: Edit purchase methods table

repos/fdbt-site/src/pages/searchOperators.tsx, repos/fdbt-site/tests/pages/__snapshots__/searchOperators.test.tsx.snap, repos/fdbt-site/tests/pages/searchOperators.test.tsx
Updating some out of date text.
n/a
=> chore: Editing some text for search operators page

repos/fdbt-site/cypress_tests/cypress/e2e/capped.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
Tests the distance journey for adding a cap product
Run cypress capped.cy.ts tests all should pass
=> feat: Pricing by distance UI test

repos/fdbt-site/cypress_tests/cypress/e2e/capped.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
To test adding a cap taps journey
Run capped.cy.ts all should pass
=> feat: UI Test for creating a capped product - pricing by taps

repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts
To ensure metro and underground modes are now included in netex.
N/A
=> feat: Added metro and underground to mode map

repos/fdbt-site/cypress_tests/cypress/e2e/capped.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/e2e.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts
Create the UI test for the capped ticket by the products
Run the cypress test for the capped ticket.
=> UI test for the capped ticket by products

repos/fdbt-site/cypress_tests/.eslintignore, repos/fdbt-site/cypress_tests/cypress/e2e/capped.cy.ts, repos/fdbt-site/cypress_tests/cypress/e2e/globalSettings/productGroups.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/e2e.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/multiOperatorGroups.ts, repos/fdbt-site/cypress_tests/cypress/support/passengerTypes.ts, repos/fdbt-site/cypress_tests/cypress/support/productGroups.ts, repos/fdbt-site/cypress_tests/cypress/support/purchaseMethods.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/cypress_tests/cypress/support/timeRestrictions.ts, repos/fdbt-site/package.json
Improve the code quality of the cypress test
Run the Cypress test
=> Fix linting issues in cypress test

repos/fdbt-site/cypress_tests/cypress/e2e/globalSettings/purchaseMethods.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/e2e.ts, repos/fdbt-site/cypress_tests/cypress/support/purchaseMethods.ts
Fix the UI test for the capped purchase and added purchase method
Run the cypress test
=> Fixing the UI test and adding for capped purchase method

fdbt-dev/Makefile, fdbt-dev/scripts/validate_this_netex.sh
Script to allow quicker validation of misc netex files.
Try using script with a random netex file.
=> chore: Added new script to makefile to validate netex file directly

fdbt-dev/data/netexData/carnetPeriodGeoZone.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/carnetReturn.xml, fdbt-dev/data/netexData/carnetSingle.xml, fdbt-dev/data/netexData/flatFareGeoZone.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/multiOpGeoZone.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodGeoZone.xml, fdbt-dev/data/netexData/periodGeoZoneGroup.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/periodPointToPoint.xml, fdbt-dev/data/netexData/return.xml, fdbt-dev/data/netexData/returnCircular.xml, fdbt-dev/data/netexData/returnCircularGroup.xml, fdbt-dev/data/netexData/returnWithExtraService.xml, fdbt-dev/data/netexData/schemeOperatorGeoZone.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, fdbt-dev/data/netexData/single.xml, fdbt-dev/data/netexData/singleGroup.xml, fdbt-dev/data/netexData/singleGroupMultipleAdults.xml, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
Reverting off peak netex changes.
n/a
=> fix: Reverting changes made for off peak netex

.github/workflows/fdbt-site_test_deployment.yml, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/api/multipleOperatorsServiceList.ts, repos/fdbt-site/src/pages/api/selectSalesOfferPackage.ts, repos/fdbt-site/src/pages/multiOperatorServiceList.tsx
UI tests were failing and we were unable to edit purchase methods for some ticket types
Make tickets of various types and edit purchase methods
=> fix: Edit Purchase method error

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/copyProduct.ts, repos/fdbt-site/src/pages/api/exports.ts, repos/fdbt-site/src/pages/api/generateReturn.ts, repos/fdbt-site/src/pages/api/salesConfirmation.ts, repos/fdbt-site/src/pages/manageProductGroup.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/products/selectExports.tsx, repos/fdbt-site/src/pages/products/services.tsx, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-site/tests/pages/api/copyProduct.test.ts, repos/fdbt-site/tests/pages/api/generateReturn.test.ts, repos/fdbt-site/tests/pages/api/salesConfirmation.test.ts, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
View and manage services for the multi modal operator
Create the tickets and edit the products
=> feat: View services for multi modal operator

repos/fdbt-site/src/pages/home.tsx
Clear up the session when navigated to home page
Edit the ticket for the fare stage and raise the error by unselecting a fare stage and click on the banner to navigate for home page and after that repeat the above step.
=> fix: Clearing up session upon navigating to home page

fdbt-dev/data/netexData/carnetPeriodGeoZone.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/carnetReturn.xml, fdbt-dev/data/netexData/carnetSingle.xml, fdbt-dev/data/netexData/flatFareGeoZone.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/multiOpGeoZone.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodGeoZone.xml, fdbt-dev/data/netexData/periodGeoZoneGroup.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/periodPointToPoint.xml, fdbt-dev/data/netexData/return.xml, fdbt-dev/data/netexData/returnCircular.xml, fdbt-dev/data/netexData/returnCircularGroup.xml, fdbt-dev/data/netexData/returnWithExtraService.xml, fdbt-dev/data/netexData/schemeOperatorGeoZone.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, fdbt-dev/data/netexData/single.xml, fdbt-dev/data/netexData/singleGroup.xml, fdbt-dev/data/netexData/singleGroupMultipleAdults.xml, repos/fdbt-netex-output/src/data/auroradb.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-site/cypress_tests/.eslintrc.js, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/timeRestrictions.ts, repos/fdbt-site/src/pages/api/deleteAllProducts.ts, repos/fdbt-site/src/pages/home.tsx
To fix the feature flag mistakes in a previous tickets, and recommitting the removed off peak netex changes.
Once deployed to test, check button works.
=> feat: Corrected feature flag and off peak netex changes

repos/exporter/lib/database.ts, repos/exporter/lib/handler.ts, repos/exporter/package.json, repos/fdbt-site/src/pages/api/deleteAllProducts.ts, repos/fdbt-types/dbTypes.ts, repos/fdbt-types/matchingJsonTypes.ts
Replacing the id with content for the capped ticket by product.
Create a capped ticket and export it via the lambda/exporter function.
=> feat: Replacing the product group id with details

repos/fdbt-site/src/interfaces/matchingJsonTypes.ts, repos/fdbt-site/src/interfaces/typeGuards.ts, repos/fdbt-site/src/pages/api/pricingPerDistance.ts, repos/fdbt-site/src/pages/definePricingPerDistance.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/tests/pages/__snapshots__/definePricingPerDistance.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/ticketRepresentation.test.tsx.snap, repos/fdbt-site/tests/pages/api/pricingPerDistance.test.ts, repos/fdbt-site/tests/pages/definePricingPerDistance.test.tsx
Provide the edit functionality to users for the flat fare product by the distance
Create the flat fare product by distance and edit the pricing per distance.
=> feat: Edit the flat fare product by distance

repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/components/DistanceRow.tsx, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/pricingPerDistance.ts, repos/fdbt-site/src/pages/capConfirmation.tsx, repos/fdbt-site/src/pages/definePricingPerDistance.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/tests/pages/__snapshots__/definePricingPerDistance.test.tsx.snap, repos/fdbt-site/tests/pages/api/pricingPerDistance.test.ts, repos/fdbt-site/tests/pages/definePricingPerDistance.test.tsx, repos/fdbt-site/tests/testData/mockData.ts
Removed the cap word from price by distance
Create the capped ticket by distance and the edit the flat fare by distance.
=> fix: removed the cap word from price by distance

repos/fdbt-site/src/components/UserDataUploads.tsx, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/interfaces/index.ts, repos/fdbt-site/src/pages/api/csvZoneUpload.ts, repos/fdbt-site/src/pages/csvUpload.tsx, repos/fdbt-site/src/pages/csvZoneUpload.tsx, repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/src/utils/apiUtils/fileUpload.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/csvUpload.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap, repos/fdbt-site/tests/pages/api/csvZoneUpload.test.ts, repos/fdbt-site/tests/pages/csvUpload.test.tsx, repos/fdbt-site/tests/pages/csvZoneUpload.test.tsx, repos/fdbt-site/tests/pages/ticketConfirmation.test.tsx
For the period ticket, service exception needs to be displayed
Create a period ticket with zeo zone
=> feat: Service exceptions to period tickets

fdbt-dev/data/matchingData/flatFareWithDistances.json, fdbt-dev/data/netexData/flatFareWithDistances.xml, repos/fdbt-netex-output/src/netex-convertor/generateAll.test.ts, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexTemplate.xml, repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts, repos/fdbt-netex-output/src/types/index.ts, repos/fdbt-site/src/interfaces/matchingJsonTypes.ts, repos/fdbt-site/src/pages/definePricingPerDistance.tsx, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-types/matchingJsonTypes.ts
Enabling the netex converter to create flat fare priced by distance netex.
Use the make file to generate all and validate all.
=> feat: Flat fare priced by distance Netex

fdbt-dev/data/netexData/carnetFlatFare.xml, fdbt-dev/data/netexData/flatFare.xml, fdbt-dev/data/netexData/flatFareGeoZone.xml, fdbt-dev/data/netexData/flatFareGroup.xml, fdbt-dev/data/netexData/flatFareWithDistances.xml, fdbt-dev/data/netexData/flatFareWithSopPrices.xml, fdbt-dev/data/netexData/schemeCarnetFlatFare.xml, fdbt-dev/data/netexData/schemeOperatorFlatFare.xml, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
Fix the validation issue on the netex.
make generate validate all command
=> fix: Add limitation to flat fares

repos/fdbt-site/src/components/DistanceRow.tsx, repos/fdbt-site/src/pages/api/pricingPerDistance.ts, repos/fdbt-site/tests/pages/api/pricingPerDistance.test.ts
Distances must be integers only on the definePricingPerDistance page
Go to the definePricingPerDistance page and try different inputs for distances only integers should be accepted
=> feat: Changing distances to integer only

repos/fdbt-site/src/data/s3.ts
Fix the issue in deleting the products
Choose operator who is having more than 1000 products and try to delete them
=> fix: Delete the products 

repos/fdbt-site/src/pages/api/pricingPerDistance.ts, repos/fdbt-site/tests/pages/api/pricingPerDistance.test.ts
Fixing the bug where integer check is done on prices
Go to the price per distance page and tests all boxes with different inputs
=> fix: integers only for price per distances 

repos/exporter/lib/database.ts, repos/exporter/lib/handler.ts, repos/fdbt-types/dbTypes.ts
Build failing:
https://github.com/fares-data-build-tool/create-data/actions/runs/4024734461/jobs/6917099421
Reverting some changes made here https://github.com/fares-data-build-tool/create-data/pull/747
Code review
Note: I maintained majority of the types to prevent typescript errors for some cap pages
=> fix: Fixing exporter by removing cap instances

repos/fdbt-admin/package-lock.json, repos/fdbt-admin/package.json, repos/fdbt-admin/src/constants.ts, repos/fdbt-admin/src/govuk.d.ts, repos/fdbt-admin/src/pages/Reporting.tsx
Added details component to reporting table, and csv download links.
N/A - to be done on test site.
=> feat: Details and csv download functionality

repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/tests/pages/ticketRepresentation.test.tsx
To be able to do a release
Code review
=> fix: Feature flag multi operator work

repos/fdbt-site/src/pages/ticketRepresentation.tsx
Feature flagging PPD (priced by distance).
Ensure not visible on preprod / prod.
=> fix: Added feature flag for PPD

repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/fixtures/fareZoneEdited.csv, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/cypress_tests/cypress/support/steps.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
Created a UI test for editing fare zone names / exempted services
Added stops to geozone tickets in product details - also editable 
Run myFares.cy.ts tests
=> feat: Edit fare zone UI test

repos/fdbt-admin/amplify/backend/auth/fdbtadmin65b519f2/fdbtadmin65b519f2-cloudformation-template.yml, repos/fdbt-admin/package-lock.json, repos/fdbt-admin/package.json, repos/fdbt-admin/src/constants.ts, repos/fdbt-admin/src/data/s3.ts, repos/fdbt-admin/src/govuk.d.ts, repos/fdbt-admin/src/pages/ListUsers.tsx, repos/fdbt-admin/src/pages/Reporting.tsx, repos/fdbt-admin/src/utils/helpers.ts
Adding 2 new reports to the admin panel, including one as a bar chart.
Deploy to environments.
=> feat: additional reports to admin panel

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/capValidity.ts, repos/fdbt-site/src/pages/api/createCaps.ts, repos/fdbt-site/src/pages/capConfirmation.tsx, repos/fdbt-site/src/pages/globalSettings.tsx, repos/fdbt-site/src/pages/manageFareDayEnd.tsx, repos/fdbt-site/src/pages/manageOperatorDetails.tsx, repos/fdbt-site/src/pages/selectCapExpiry.tsx, repos/fdbt-site/src/pages/selectCapValidity.tsx, repos/fdbt-site/src/pages/viewCaps.tsx, repos/fdbt-site/src/pages/viewOperatorGroups.tsx, repos/fdbt-site/src/pages/viewPassengerTypes.tsx, repos/fdbt-site/src/pages/viewPurchaseMethods.tsx, repos/fdbt-site/tests/pages/__snapshots__/capConfirmation.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/capValidity.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewCaps.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewOperatorGroups.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewPurchaseMethods.test.tsx.snap, repos/fdbt-site/tests/pages/api/capValidity.test.ts, repos/fdbt-site/tests/pages/api/managePassengerTypes.test.ts, repos/fdbt-site/tests/pages/capConfirmation.test.tsx, repos/fdbt-site/tests/pages/capValidity.test.tsx, repos/fdbt-site/tests/pages/viewCaps.test.tsx, repos/fdbt-site/tests/testData/mockData.ts
Adding the cap expiry in operator settings
Create and update the expiry in cap
=> feat: Adding the cap expiry in operator settings

.github/workflows/fdbt-site_test_deployment.yml, .github/workflows/fdbt-site_test_deployment_ui_test.yml
=> splitting up pipeline

repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-emailer/handler.ts
If a price only existed in the inbound fare zones of a return ticket, the id for that price was not being created. The change makes it so that we look inside both inbound and outbound fare zones for unique prices.
To be tested with matching JSON of failing product from Prod.
=> fix: return tickets prices in netex fix

repos/exporter/lib/handler.ts
Exporter was not happy with periodValidity being in a period ticket, so added additional check.
n/a
=> fix: Exporter type checking

.github/workflows/fdbt-site_test_deployment.yml, .github/workflows/fdbt-site_test_deployment_ui_test.yml
=> adding checkout step

fdbt-dev/data/netexData/carnetPeriodGeoZone.xml, fdbt-dev/data/netexData/flatFareGeoZone.xml, fdbt-dev/data/netexData/flatFareWithExemptServices.xml, fdbt-dev/data/netexData/flatFareWithExemptStops.xml, fdbt-dev/data/netexData/hybridPeriod.xml, fdbt-dev/data/netexData/hybridPeriodWithExemptServicesAndStops.xml, fdbt-dev/data/netexData/multiOpFlatFareGeoZone.xml, fdbt-dev/data/netexData/multiOpGeoZone.xml, fdbt-dev/data/netexData/periodGeoZone.xml, fdbt-dev/data/netexData/periodGeoZoneGroup.xml, fdbt-dev/data/netexData/schemeCarnetPeriod.xml, fdbt-dev/data/netexData/schemeOperatorGeoZone.xml, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/types/index.ts
Changing the stop reference in the netex for zone tickets
Create the netex for the zone tickets
=> feat: Changing the stop reference in netex

.github/workflows/fdbt-netex-output_test_deployment.yml, repos/fdbt-netex-output/src/netex-convertor/handler.ts
Ubuntu 18.04 is being deprecated, so we're replacing it with 20.04 
Pipeline should build.
=> fix: Changing ubuntu image to 20.04

.github/workflows/fdbt-netex-output_test_deployment.yml
=> installing glib

fdbt-dev/data/matchingData/hybridPeriod.json, fdbt-dev/data/matchingData/hybridPeriodWithExemptServicesAndStops.json, fdbt-dev/data/matchingData/schemeOperatorMultiServices.json, fdbt-dev/data/netexData/carnetPeriodGeoZone.xml, fdbt-dev/data/netexData/carnetPeriodMultiService.xml, fdbt-dev/data/netexData/carnetReturn.xml, fdbt-dev/data/netexData/hybridPeriod.xml, fdbt-dev/data/netexData/hybridPeriodWithExemptServicesAndStops.xml, fdbt-dev/data/netexData/multiOpGeoZone.xml, fdbt-dev/data/netexData/multiOpMultiServices.xml, fdbt-dev/data/netexData/periodGeoZone.xml, fdbt-dev/data/netexData/periodGeoZoneGroup.xml, fdbt-dev/data/netexData/periodMultiService.xml, fdbt-dev/data/netexData/periodPointToPoint.xml, fdbt-dev/data/netexData/return.xml, fdbt-dev/data/netexData/returnCircularGroup.xml, fdbt-dev/data/netexData/returnWithExtraService.xml, fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml, fdbt-dev/data/netexData/schemeCarnetPeriod.xml, fdbt-dev/data/netexData/schemeOperatorGeoZone.xml, fdbt-dev/data/netexData/schemeOperatorMultiServices.xml, fdbt-dev/data/netexData/schoolPeriodMultiService.xml, repos/exporter/lib/handler.ts, repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts, repos/fdbt-types/matchingJsonTypes.ts
Adding the usage validity period in the netex file
Create the netex file or the export of the product made with fareDay end
=> feat: Modifying the usage validity period

repos/fdbt-site/src/pages/ticketConfirmation.tsx, repos/fdbt-site/tests/pages/ticketConfirmation.test.tsx
The "change" in ticket confirmation is redirecting the user to multipleProducts instead of pointToPointPeriodProduct
Create a point to point period/school ticket and click on Change in the ticket confirmation page.
=> fix: Fixing the bug for the change in the redirection of point to point

fdbt-dev/data/matchingData/schoolServicePointToPoint.json, fdbt-dev/data/netexData/schoolServicePointToPoint.xml, repos/fdbt-site/src/pages/api/selectExports.ts, repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/tests/pages/api/selectExports.test.ts, repos/fdbt-site/tests/pages/products/__snapshots__/exports.test.tsx.snap, repos/fdbt-site/tests/pages/products/exports.test.tsx
School P2P period had missing time restrictions in the json file.
N/A
=> fix: Fixing test data

repos/fdbt-site/cypress_tests/cypress/support/steps.ts
UI test was breaking as time restrictions arent present for school tickets.
UI tests should pass
=> fix: Fixing editing of school ticket in UI test

repos/fdbt-site/src/pages/searchOperators.tsx, repos/fdbt-site/tests/pages/searchOperators.test.tsx
Page state wasnt being handled properly, this fix should avoid bugs with adding and removing. Also re-alphabetises the Operator list.
Create a group on test env and add operators then remove operators, back and forth.
=> fix: Search operators page fix

repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/api/csvZoneUpload.ts, repos/fdbt-site/src/pages/api/serviceList.ts, repos/fdbt-site/src/pages/editFareStageMatching.tsx, repos/fdbt-site/src/pages/inboundMatching.tsx, repos/fdbt-site/src/pages/matching.tsx, repos/fdbt-site/src/pages/missingStops.tsx, repos/fdbt-site/src/pages/outboundMatching.tsx, repos/fdbt-site/src/utils/apiUtils/matching.ts, repos/fdbt-site/src/utils/apiUtils/userData.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/missingStops.test.tsx.snap, repos/fdbt-site/tests/pages/missingStops.test.tsx, repos/fdbt-site/tests/utils/api/matching.test.ts
A new page to render if the operator's service has missing stops from the NaPTAN dataset.
Use a service which has missing stops, to check redirect is working.
=> feat: Missing stops page

.github/workflows/fdbt-site_test_deployment.yml, repos/fdbt-site/src/constants/attributes.ts, repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/editFareStageMatching.tsx, repos/fdbt-site/src/pages/missingStops.tsx, repos/fdbt-site/src/utils/apiUtils/matching.ts, repos/fdbt-site/src/utils/sessions.ts, repos/fdbt-site/tests/pages/__snapshots__/missingStops.test.tsx.snap, repos/fdbt-site/tests/pages/direction.test.tsx, repos/fdbt-site/tests/pages/missingStops.test.tsx, repos/fdbt-site/tests/utils/api/matching.test.ts
New page to explain to the user why their service cannot be used to create Netex - because there is a missing stop in the Naptan database that needs to be added.
Attempt to create a product with a service that has a stop in the service data which is not in the Naptan dataset.
=> feature: missing stops page

.github/workflows/exporter_dev_deployment.yml, .github/workflows/fdbt-netex-output_dev_deployment.yml, .github/workflows/fdbt-reference-data-service_dev_deployment.yml, .github/workflows/fdbt-site_dev_deployment.yml
=> add new pipelines

repos/fdbt-reference-data-service/src/retrievers/package.json, repos/fdbt-reference-data-service/src/uploaders/package.json
=> add packages

repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/tests/pages/ticketRepresentation.test.tsx
Removing feature flags for multi op flat fares and flat fare priced by distance products.
In non-test env, multi op flat fares and flat fare priced by distance will be available in the radio buttons.
=> feat: Turning on multi op flat fares and flat fare priced by distance

.github/workflows/fdbt-netex-output_preprod_deployment.yml, .github/workflows/fdbt-netex-output_prod_deployment.yml, .github/workflows/fdbt-netex-output_test_deployment.yml
Updated the path for module download
Rerun the netex output pipeline and check for lxml issue in the logs
=> Fix netex validator pipeline

.github/workflows/fdbt-reference-data-service_preprod_deployment.yml, .github/workflows/fdbt-reference-data-service_prod_deployment.yml, .github/workflows/fdbt-reference-data-service_test_deployment.yml
=> updated the pipelines to point at the right directory

.github/workflows/fdbt-reference-data-service_preprod_deployment.yml, .github/workflows/fdbt-reference-data-service_prod_deployment.yml, .github/workflows/fdbt-reference-data-service_test_deployment.yml
=> Fdbt ref ds pl fix

.github/workflows/fdbt-reference-data-service_preprod_deployment.yml, .github/workflows/fdbt-reference-data-service_prod_deployment.yml
=> Reverting prod and pre-prod pipeline changes

repos/fdbt-site/package-lock.json, repos/fdbt-site/src/pages/api/exports.ts, repos/fdbt-site/src/pages/products/selectExports.tsx, repos/fdbt-site/tests/pages/products/__snapshots__/multiOperatorProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/otherProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/multiOperatorProducts.test.tsx, repos/fdbt-site/tests/pages/products/otherProducts.test.tsx
Pending services were not exporting when they should be.
-Updated dependency 
-Fixed tests
-Pending services fix removed filter for non-active services
=> feat: Pending Services

.github/workflows/fdbt-site_test_deployment.yml
=> Update fdbt-site_test_deployment.yml to node 16

.github/workflows/fdbt-site_test_deployment.yml, repos/fdbt-site/package-lock.json
Revert upgrade of caniuse-lite and change workflow file back to 14
=> Revert changes

.github/workflows/fdbt-site_test_deployment.yml
=> chore: remove cypress tests from workflow

repos/fdbt-site/package-lock.json, repos/fdbt-site/package.json, repos/fdbt-site/server/index.ts, repos/fdbt-site/src/pages/api/serviceList.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/ticketRepresentation.tsx, repos/fdbt-site/tests/pages/__snapshots__/ticketRepresentation.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx, repos/fdbt-site/tests/pages/ticketRepresentation.test.tsx
Remove this user journey but retain code for possible re-release later
Option is offered on flat fare journey page /ticketRepresentation
=> feat:  Feature flag price by distance

.tool-versions, Makefile, docs/guides/getting-started.md, fdbt-dev/.gitignore, fdbt-dev/Makefile, fdbt-dev/docker-compose.yml, fdbt-dev/scripts/trigger_netex_convertor.sh, fdbt-dev/scripts/trigger_netex_emailer.sh, fdbt-dev/scripts/trigger_netex_validator.sh, fdbt-dev/scripts/wait_for_mysql.sh, fdbt-dev/scripts/wait_for_s3_sns.sh, repos/exporter/lib/atcoCheckerHandler.ts, repos/exporter/lib/handler.ts, repos/fdbt-netex-output/package.json, repos/fdbt-netex-output/src/data/s3.ts, repos/fdbt-site/Makefile, repos/fdbt-site/package.json, repos/fdbt-site/server/middleware/sessions.ts, repos/fdbt-site/src/data/s3.ts
* Upgrade localstack to address issues with running the site locally
* Remove references to using nvm in favour of asdf
=> localstack fix

repos/fdbt-site/src/pages/managePassengerGroup.tsx, repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap
For accessibility the label ids need to match the input
Check on page using accessibility tool or code review
=> fix: Missing label issue

repos/fdbt-site/src/pages/contact.tsx, repos/fdbt-site/tests/pages/__snapshots__/contact.test.tsx.snap
To meet accessibility standard
=> fix: feedback text

repos/fdbt-site/src/components/OperatorGroupCard.tsx, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/components/ProductGroupCard.tsx, repos/fdbt-site/src/pages/reuseOperatorGroup.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/src/pages/selectTimeRestrictions.tsx, repos/fdbt-site/tests/components/__snapshots__/ProductGroupCard.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/reuseOperatorGroup.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/selectPurchaseMethods.test.tsx.snap
EXPECTED - A <label> element that is associated to a form control but does not contain text will not present any information about the form control to the user. Example:
<label class="theme-switch" for="checkbox">
Enable dark mode
</label>
<input type="checkbox" id="checkbox" />
<span class="slider round"></span>
ACTUAL:
OCCURENCE 1
Open image-20240624-093607.png
image-20240624-093607.png
[Select Passenger Type - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/selectPassengerType)
<label class="govuk-label govuk-radios__label"></label>
OCCURENCE 2:
[Select Time Restrictions - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/selectTimeRestrictions)
Open image-20240624-155355.png
image-20240624-155355.png
<label class="govuk-label …
=> fix: Missing form label

repos/fdbt-site/src/design/modules/_cards.scss, repos/fdbt-site/src/design/modules/_components.scss
EXPECTED: 
Expected contrast ratio of 4.5:1
[WebAIM: Contrast and Color Accessibility - Understanding WCAG 2 Contrast and Color Requirements](https://webaim.org/articles/contrast/)
ACTUAL:
OCCURENCE 1
Element has insufficient colour contrast of 4.26
Open image-20240621-123927.png
image-20240621-123927.png
Location: <button class="govuk-link govuk-!-font-size-16 govuk-!-font-weight-regular actions__delete">Delete</button>
OCCURENCE 2 - [Time restrictions (dft-cfd.com)](https://preprod.dft-cfd.com/viewTimeRestrictions)
Open image-20240624-154600.png
image-20240624-154600.png
OCCURENCE 3 - [Purchase methods (dft-cfd.com)](https://preprod.dft-cfd.com/viewPurchaseMethods)
Open image-20240625-123036.png
image-20240625-123036.png
OCCURENCE 4 -  [Search Operators - Create Fares Data Service …
=> fix: LOW Colour Contrast

repos/fdbt-site/src/components/OperatorGroupCard.tsx, repos/fdbt-site/src/components/PassengerTypeCard.tsx, repos/fdbt-site/src/components/ProductGroupCard.tsx, repos/fdbt-site/src/pages/products/otherProducts.tsx, repos/fdbt-site/src/pages/selectTimeRestrictions.tsx, repos/fdbt-site/tests/components/__snapshots__/ProductGroupCard.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/otherProducts.test.tsx.snap
Other products page, cards including time restrictions should not have accessibility issues on their pages
=> fix: Accessibility issues

repos/fdbt-site/src/pages/api/ticketConfirmation.ts, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/tests/pages/api/ticketConfirmation.test.ts, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
Enable caps on all environments
Go through the create ticket flow and observe the select caps step is shown after the ticket confirmation page
=> Caps feature flag removal

repos/fdbt-site/cypress_tests/cypress/e2e/myFares/myFares.cy.ts, repos/fdbt-site/cypress_tests/cypress/support/helpers.ts, repos/fdbt-site/src/layout/Navigation.tsx, repos/fdbt-site/src/pages/home.tsx, repos/fdbt-site/src/pages/products/multiOperatorProducts.tsx, repos/fdbt-site/src/pages/products/multiOperatorProductsExternal.tsx, repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/multiOperatorProducts.test.tsx.snap
- more changes of existing multi-operator products to include (internal)
- add new link on home page for multi-operator external
- assert home page has new link and it links to a new multi-operators external dashboard page (stubbed at the moment)
=> CFDS-307 home page changes

repos/fdbt-site/src/data/auroradb.ts, repos/fdbt-site/src/pages/fareType.tsx, repos/fdbt-site/src/pages/products/multiOperatorProductsExternal.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/utils/index.test.ts, repos/fdbt-site/src/utils/index.ts, repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap, repos/fdbt-site/tests/pages/products/productDetails.test.tsx, repos/fdbt-site/tests/testData/mockData.ts
- amend product details page to display for multi-operator prodect non-lead operators (services variation only)
=> CFDS-316-product-details-page-changes

repos/fdbt-site/src/interfaces/matchingJsonTypes.ts, repos/fdbt-site/src/pages/api/csvZoneUpload.ts, repos/fdbt-site/src/pages/api/serviceList.ts, repos/fdbt-site/src/pages/csvZoneUpload.tsx, repos/fdbt-site/src/pages/definePricingPerDistance.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/serviceList.tsx, repos/fdbt-site/tests/pages/products/productDetails.test.tsx
- multi-operator external fare zone flow for non-lead operators
=> CFDS-317 non lead operator flow - fare zone

repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx, repos/fdbt-site/src/components/OperatorGroupCard.tsx, repos/fdbt-site/src/components/Pagination.tsx, repos/fdbt-site/src/components/RadioButtons.tsx, repos/fdbt-site/src/components/RadioConditionalInput.tsx, repos/fdbt-site/src/pages/multiOperatorServiceList.tsx, repos/fdbt-site/src/pages/multipleOperators.tsx, repos/fdbt-site/src/pages/products/pointToPointProducts.tsx, repos/fdbt-site/src/pages/products/productDetails.tsx, repos/fdbt-site/src/pages/products/services.tsx, repos/fdbt-site/src/pages/reuseOperatorGroup.tsx, repos/fdbt-site/src/pages/searchOperators.tsx, repos/fdbt-site/src/pages/selectPassengerType.tsx, repos/fdbt-site/src/pages/selectPurchaseMethods.tsx, repos/fdbt-site/src/pages/viewOperatorGroups.tsx, repos/fdbt-site/src/pages/viewPurchaseMethods.tsx, repos/fdbt-site/src/pages/viewTimeRestrictions.tsx, repos/fdbt-site/tests/components/__snapshots__/RadioButtons.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/multipleOperators.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/searchOperators.test.tsx.snap, repos/fdbt-site/tests/pages/__snapshots__/viewTimeRestrictions.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap, repos/fdbt-site/tests/pages/products/__snapshots__/services.test.tsx.snap
- add missing react map keys across codebase
- remove a few unnecessary react fragments
=> CFDS-324 react map keys

repos/exporter/lib/handler.ts, repos/fdbt-netex-output/.eslintrc.js, repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts, repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts, repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.test.ts, repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts
to optimise the netex output, empty fare zones and structure elements will be omitted
=> feat: remove empty fare zones and structures from netex output

repos/fdbt-site/src/pages/products/exports.tsx, repos/fdbt-site/src/pages/products/selectExports.tsx
- reinstate cancel button (this will show next to the export rather than at the top of the page)
- fix redirect on selectExports page
- fix button to show failed export details popup
=> fix: Export page fixes

repos/fdbt-site/src/data/cognito.ts, repos/fdbt-site/src/pages/account.tsx, repos/fdbt-site/tests/pages/account.test.tsx, repos/fdbt-site/tests/testData/mockData.ts
fix to retrieve email pref from cognito rather than fetching from id token
=> fix: account page - email preference

repos/fdbt-reference-data-service/src/uploaders/csv_uploader/db_queries.py
=> fix: update db queries when loading data from s3 to include char set
