- fdbt-dev/data/matchingData/schemeOperatorGeoZone.json
- repos/fdbt-netex-output/.eslintrc.js
- repos/fdbt-netex-output/package-lock.json
- repos/fdbt-netex-output/package.json
- repos/fdbt-netex-output/src/types/index.ts
- repos/fdbt-site/src/pages/carnetProductDetails.tsx
- repos/fdbt-site/tests/pages/__snapshots__/carnetProductDetails.test.tsx.snap
- repos/fdbt-site/tests/pages/api/multipleProducts.test.ts
-   To allow scheme operators to correctly generate netex.
-   Run make command to generate scheme operator netex. …
> fix: scheme operator netex not generating

- repos/fdbt-site/src/pages/api/multipleProducts.ts
- repos/fdbt-site/tests/pages/api/multipleProducts.test.ts
-   No expiry option for carnet's were forcing users to enter a number, when they shouldnt have been.
-   Use locally and test the situation.
- 
- …
> fix: Fixed bug around carnet no expiry

- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/pages/createdFiles.tsx
- repos/fdbt-site/src/pages/fareType.tsx
- repos/fdbt-site/tests/pages/__snapshots__/createdFiles.test.tsx.snap
- repos/fdbt-site/tests/pages/createdFiles.test.tsx
-   To allow the user to see a distinction between their normal fares and carnet fares in the created files page. Also, to turn on carnet in prod for all fares apart from scheme operators.
-   Add a carnetDetails : {} to the first product in some matching JSON, and make sure the created files page sees this locally. 
-   [ ] build - Changes that affect the build system or external …
> feat: Added distinction for carnets in created files page and enabled carnet in prod

- repos/fdbt-netex-output/src/netex-validator/main.py
-   We want the slack channel to alert us when files are not validated, not when they are. This change removes the code which outputs to our slack on success.
-   None required, will be able to test when merged in by creating a netex file.
-   [ ] ci - Changes to our …
> chore: Removed code which outputs to slack on successful validation

- fdbt-aws/sql/l.addEndDateColumnTotxcOperatorLine.sql
- fdbt-dev/sql/txcOperatorLine.sql
- repos/fdbt-reference-data-service/src/uploaders/tests/test_xml_uploader.py
- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
- repos/fdbt-site/src/data/auroradb.ts
-   Filter ended services.
-   Deploy to test environment, then trigger the txcRetriever, once that path is complete.
-   Connect to the MySQL database on test.
-   Add an endDate for a few services that belong to the national operator code 'BLAC'
-   Navigate to to the site and get to the Service List page using the `BLAC` national operator code.
-   You should only see services whose endDate is less than or equal to today's date.
-   [ ] test …
> feat: CFD-337 filter ended services

- repos/fdbt-site/src/design/Layout.scss
- repos/fdbt-site/src/design/main.scss
- repos/fdbt-site/src/design/modules/_components.scss
- repos/fdbt-site/src/design/modules/_header.scss
- repos/fdbt-site/src/design/modules/_layout.scss
- repos/fdbt-site/src/design/modules/_pages.scss
- repos/fdbt-site/src/design/modules/_phase-banner.scss
- repos/fdbt-site/src/layout/Header.tsx
- repos/fdbt-site/src/layout/Layout.tsx
- repos/fdbt-site/src/layout/Navigation.tsx
- repos/fdbt-site/src/layout/PhaseBanner.tsx
- repos/fdbt-site/src/pages/_app.tsx
- repos/fdbt-site/src/pages/globalSettings.tsx
- repos/fdbt-site/src/pages/home.tsx
- repos/fdbt-site/src/pages/index.tsx
- repos/fdbt-site/tests/layout/__snapshots__/AlphaBanner.test.tsx.snap
- repos/fdbt-site/tests/layout/__snapshots__/Header.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap
- repos/fdbt-site/tests/pages/home.test.tsx
This ticket creates the user interface for the global settings page and also displays a link to "operator settings" on the home page provided it's not hosted on the production environment.
Spin the site up and head to http://localhost:5555/globalSettings and check it looks like the ticket says it should
-   [ ] build - Changes that affect the build system or external dependencies …
> feat: CFD-295 add the global settings page

- repos/fdbt-site/src/design/modules/_cards.scss
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
In order to tidy up the passenger page design this ticket has:
- Included underlying passenger type on each card
- Allowed max 2 lines (44 Characters) for proof documents, any more than this and it's truncated with '...' at end of second line
- Every box matches the size of the ones with 2 lines for proof documents
-  Define some passenger types (preferably some with all verification documents)
-  Go to http://localhost:5555/viewPassengerTypes and check that all three objectives in the description still hold true
-   [ ] refactor - A code change that neither fixes a bug nor …
> fix: cfd 355 passenger page design issues

- fdbt-aws/cloudformation/service/eu-west-2/s3.yml
- repos/fdbt-site/tests/pages/selectSalesOfferPackage.test.tsx
-   Removed the lifecycle policy on the `fdbt-raw-user-data` S3 bucket.
-   In 30 days time, check the bucket to see if files from 30 days ago remain. …
> feat: CFD-167 remove the bucket lifecycle policy and make linter happy again

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/api/managePassengerGroup.ts
- repos/fdbt-site/src/pages/api/managePassengerTypes.ts
- repos/fdbt-site/src/pages/managePassengerGroup.tsx
- repos/fdbt-site/src/pages/managePassengerTypes.tsx
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
- repos/fdbt-site/tests/pages/__snapshots__/managePassengerGroup.test.tsx.snap
- repos/fdbt-site/tests/pages/api/managePassengerGroup.test.ts
- repos/fdbt-site/tests/pages/managePassengerTypes.test.tsx
-   Fix issue with reloading passenger types with errors in global settings
-   Make sure that when editing / creating passenger types, the errors from previously editing / creating don't come through
-   Repeat for Groups
-   [ ] ci - Changes to our CI configuration …
> fix: CFD-361 Fix issue with reloading passenger types with errors in global settings

- repos/fdbt-site/src/pages/api/managePassengerGroup.ts
- repos/fdbt-site/tests/pages/api/managePassengerGroup.test.ts
-   Update validation logic on group creation to stop a group being created with two identical underlying types.
-   First create two individual passenger types that are both of type `Adult`, for example, `Regular Adult` and `Adults`.
-   Then try creating a group that has both those types. You should see an error as this is not allowed.
-   [ ] build - Changes that affect the …
> feat: cfd-384 update validation logic on group creation

- fdbt-aws/cloudformation/service/eu-west-2/fargate.yml
- repos/fdbt-site/src/pages/api/csvZoneUpload.ts
- repos/fdbt-site/src/utils/internalLogger.ts
- repos/fdbt-site/src/utils/logger.ts
- repos/fdbt-site/src/utils/nextLogger.ts
-   Make all logs JSON and only alert on errors
-   Trigger an error on site - should be alerted
-   All logs in cloudwatch for site should be JSON format with a "level" property
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, …
> chore: CFD-365 Make all logs JSON and only alert on errors

- repos/fdbt-reference-data-service/src/uploaders/serverless.yml
-   Increases the throttle threshold for TxcUploader lambda to prevent alarms
-   Trigger the TxcRetriever lambda and ensure a throttle alarm is not triggered …
> chore: cfd-412 increase lambda throttle alarm threshold

- fdbt-dev/data/netexData/flatFareGroup.xml
- fdbt-dev/data/netexData/periodGeoZoneGroup.xml
- fdbt-dev/data/netexData/returnCircularGroup.xml
- fdbt-dev/data/netexData/singleGroup.xml
- repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts
- repos/fdbt-site/src/pages/api/managePassengerGroup.ts
- repos/fdbt-site/tests/pages/api/managePassengerGroup.test.ts
-   Allowing users to enter the same passenger type (e.g. Adult) into the same group, and changing netex repo to allow for this also.
-   Ensure UI allows this change, and netex repo supports it.
-   [ ] ci - Changes to our CI configuration files and scripts (example …
> fix: Allow same passenger types in group

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/design/modules/_layout.scss
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/pages/api/apiUtils/index.ts
- repos/fdbt-site/src/pages/api/defineTimeRestrictions.ts
- repos/fdbt-site/src/pages/api/manageFareDayEnd.ts
- repos/fdbt-site/src/pages/api/manageTimeRestriction.ts
- repos/fdbt-site/src/pages/api/register.ts
- repos/fdbt-site/src/pages/manageFareDayEnd.tsx
- repos/fdbt-site/src/pages/manageTimeRestriction.tsx
- repos/fdbt-site/src/pages/viewTimeRestrictions.tsx
- repos/fdbt-site/src/utils/index.ts
- repos/fdbt-site/src/utils/nextLogger.ts
- repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/manageTimeRestriction.test.tsx.snap
- repos/fdbt-site/tests/pages/api/defineTimeRestrictions.test.ts
- repos/fdbt-site/tests/pages/api/manageTimeRestriction.test.ts
- repos/fdbt-site/tests/pages/manageTimeRestriction.test.tsx
-   Adds fare day end as an option for time restrictions
-   Check that the fare day end option on the time restrictions page functions correctly
-   Check the validation
-   Check that you can use a fare day end time restriction in the fare journey and you generate NetEX with the correct value in the time restriction
-   [ ] build - Changes that affect the build system or external …
> feat: CFD-387 Fare day end as an option for time restrictions

- repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx
- repos/fdbt-site/src/components/UnableToDeletePopup.tsx
- repos/fdbt-site/src/pages/globalSettings.tsx
- repos/fdbt-site/src/pages/manageFareDayEnd.tsx
- repos/fdbt-site/src/pages/selectPassengerType.tsx
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
- repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/selectPassengerType.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap
Change titlestyle from 'm' to 'xl'
Check that on /globalSettings page "Settings overview" is styled in XL size
-   [ ] chore - Other changes that …
> fix: CFD-408 settings overview heading

- repos/fdbt-site/cypress_tests/cypress/support/index.ts
- repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx
- repos/fdbt-site/src/components/PassengerTypeCard.tsx
- repos/fdbt-site/src/components/RadioConditionalInput.tsx
- repos/fdbt-site/src/constants/featureFlag.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/pages/periodValidity.tsx
- repos/fdbt-site/src/pages/selectPassengerType.tsx
- repos/fdbt-site/src/pages/selectPeriodValidity.tsx
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
- repos/fdbt-site/src/pages/viewPurchaseMethods.tsx
- repos/fdbt-site/src/pages/viewTimeRestrictions.tsx
- repos/fdbt-site/tests/components/GlobalSettingsViewPage.test.tsx
- repos/fdbt-site/tests/pages/__snapshots__/globalSettingsPeriodValidity.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/periodValidity.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/selectPassengerType.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/viewPassengerTypes.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/viewPurchaseMethods.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/viewTimeRestrictions.test.tsx.snap
- repos/fdbt-site/tests/pages/selectPassengerType.test.tsx
- repos/fdbt-site/tests/pages/viewPassengerTypes.test.tsx
- repos/fdbt-site/tests/pages/viewPurchaseMethods.test.tsx
- repos/fdbt-site/tests/pages/viewTimeRestrictions.test.tsx
- repos/fdbt-site/tests/testData/mockData.ts
-   Disable auto selection of fare day end option + UI test fixes
-   Make sure the fare day end option on the period validity page is not auto selected …
> fix: Disable auto selection of fare day end option + UI test fixes

- repos/fdbt-site/src/utils/apiUtils/matching.ts
-   Fix error when parsing unassigned fare stages
-   Check the box that allows you to skip using all fare stages for a return stop mapping
-   Check you get no errors …
> fix: Error when parsing unassigned fare stages

- repos/fdbt-site/src/pages/fareType.tsx
- repos/fdbt-site/src/pages/manageOperatorDetails.tsx
- repos/fdbt-site/src/utils/globalSettings.ts
- repos/fdbt-site/tests/pages/fareType.test.tsx
-   To ensure scheme operators fill out their operator details before creating netex.
-  Run locally and use disabeAuth=scheme , then attempt to create netex. …
> feat: force scheme operators to fill out operator details

- repos/exporter/lib/database.ts
- repos/exporter/lib/handler.ts
- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/pages/api/manageTimeRestriction.ts
- repos/fdbt-site/src/pages/viewTimeRestrictions.tsx
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/tests/pages/api/apiUtils/userData.test.ts
- repos/fdbt-site/tests/pages/api/salesConfirmation.test.ts
- repos/fdbt-site/tests/testData/mockData.ts
- shared/dbTypes.ts
- shared/matchingJsonTypes.ts
-   To make the site update the matching JSON with ID's, and the exporter uses these ID's to find the appropriate time restriction.
-   Testing has been done with Jake to deploy and use the lambda test function.
-   [ ] ci - Changes to our CI configuration files and …
> feat: time restrictions use id's

- repos/fdbt-site/src/pages/api/fareType.ts
- repos/fdbt-site/tests/pages/api/fareType.test.ts
-  Stops any issues where user navigates back after partially completing a journey, and starts another one.
-   Run site locally, and navigate back after starting a journey, ensure session is cleared. …
> fix: Cleared session in faretype api

- repos/fdbt-netex-output/package-lock.json
- repos/fdbt-netex-output/package.json
- repos/fdbt-netex-output/src/netex-validator/package-lock.json
- repos/fdbt-netex-output/src/netex-validator/package.json
- repos/fdbt-reference-data-service/src/retrievers/package-lock.json
- repos/fdbt-reference-data-service/src/retrievers/package.json
- repos/fdbt-reference-data-service/src/uploaders/package-lock.json
- repos/fdbt-reference-data-service/src/uploaders/package.json
-   The plugins were missed from the package.json, so weren't available in the pipeline
-   Serverless should deploy successfully when merged
-   [ …
> fix: cfd 486 serverless log retention plugin install added

- fdbt-aws/cloudformation/service/eu-west-2/cloudfront.yml
Using the latest and recommended CloudFront TLS Security policy, removes
ciphers that are potentially vulnerable from being supported for TLS
connections to the site
-   Do we have a list of supported browsers, some very old clients (IE6 etc) may not be able to connect
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, …
> feat: Updating to 2021 CloudFront Security Policy

- fdbt-aws/cloudformation/service/us-east-1/lambda.yml
- repos/fdbt-site/server/middleware/security.ts
Added to fallback CSP in the Cloudfront Lambda@edge:
'connect-src' directive restricts the URLs which can be loaded using script interfaces
'upgrade-insecure-requests' directive instructs user agents to treat all HTTP urls as though they are HTTPS URLs
Added to the site CSP:
'upgrade-insecure-requests' directive instructs user agents to treat all HTTP urls as though they are HTTPS URLs
- Ensure no resources fail to load (as they don't have a HTTPS source)
-   [ ] perf - A code change that improves …
> feat: Updating CSP with additional directives

- fdbt-aws/cloudformation/service/us-east-1/waf.yml
Adding a WAF to attach to the CloudFront distribution of the Fargate
hosted site
Using AWS managed rule groups as a baseline, with additional account
level protection of network traffic provided by AWS Shield
-   Particular attention to file uploads as these are most likely to trigger WAF rules
-   [ ] build - Changes that affect the build system or external dependencies (example …
> feat: Adding WAF with Managed Rule Sets

- repos/fdbt-site/src/components/MatchingBase.tsx
- repos/fdbt-site/src/pages/api/inboundMatching.ts
- repos/fdbt-site/src/pages/inboundMatching.tsx
- repos/fdbt-site/src/pages/matching.tsx
- repos/fdbt-site/src/pages/outboundMatching.tsx
- repos/fdbt-site/tests/components/MatchingBase.test.tsx
- repos/fdbt-site/tests/pages/__snapshots__/inboundMatching.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/matching.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/outboundMatching.test.tsx.snap
- repos/fdbt-site/tests/pages/api/inboundMatching.test.ts
- repos/fdbt-site/tests/pages/inboundMatching.test.tsx
-   To stop users from not using all fare stages across both matching pages, which results in invalid netex being created.
-   Run locally and for a return ticket, attempt to use some of the fare stages on each matching page, leaving one or more unused entirely.
-   [ …
> fix: Added warning around users not using all their fare stages

- repos/fdbt-site/src/pages/api/inboundMatching.ts
- repos/fdbt-site/src/utils/apiUtils/matching.ts
-   Ensuring users can use the inbound and outbound matching pages to miss out fare stages where needed, but not entirely.
-   Run locally and create a return ticket, using or not using fare stages in all scenarios.
-   [ ] ci - Changes to our CI configuration files …
> fix: matching page workaround fix

- fdbt-aws/cloudformation/service/us-east-1/waf-test.yml
This inverts the WAF to be allow all, as we need public access in prod
Then in test the rules will block non-ip set included ip addresses
- Ensure Test is only accessible to allowed IPs (take your IP out of IP Set to test)
- Ensure Preprod is accessible
-   [ ] ci - …
> feat: rewrite of WAF rule logic cfd-510

- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
-   We currently dont handle the exceptions thrown if TXC files do not have journey patterns or journey pattern sections. This change ensures we do not continue with the database transaction if this is the case.
-   Reference data import.
-   [ ] ci - Changes to our …
> feat: Check to find if journey patterns and journey pattern sections exist in TXC

- repos/fdbt-netex-output/serverless.yml
-   Set reserved concurrency for netex converter
-   Run a big export and check there are no errors with the DB running out of connections
-   [ ] …
> fix: CFD-535 Set reserved concurrency for netex converter

- repos/exporter/lib/referenceData/tableRenamer.ts
- repos/fdbt-site/tests/pages/products/__snapshots__/otherProducts.test.tsx.snap
-   We'll disable the foreign key checks before dropping the old tables, then we will re-enable them after the drop is complete.
-   Run the lambdas in an environment (e.g. test) where old tables exist. …
> fix: cfd-585 - foreign key checks

- repos/fdbt-site/package-lock.json
fix: disable foreign key checks before dropping the old tables, then enabling the check straight after (#354)
> Preprod Release

- repos/fdbt-reference-data-service/src/retrievers/serverless.yml
Now that the Lambda invokes itself, we only need one schedule otherwise
we'll end up with three executions and a race condition in the
clearing down and data uploads
- N/A …
> fix: cfd-397 remove lambda schedule

- repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts
- repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
-   Stop altering of the original fare zones array being passed in, this was causing the fare zones XML element to be wrong.
-   Do an export on test for FSRV and check scheduled stops and farezones (send to Steve for verification)
-   [ ] ci - Changes to our CI …
> fix: cfd-566 stop altering of the original fare zones array being passed in

- fdbt-aws/cloudformation/service/eu-west-2/fargate.yml
- fdbt-aws/grafana/general/business-intelligence.json
- fdbt-aws/grafana/general/kpi.json
- fdbt-aws/grafana/services/netex-output.json
- fdbt-aws/grafana/services/reference-data.json
- fdbt-aws/grafana/services/site.json
- fdbt-aws/grafana/services/txc-retrieval.json
Upgrades Grafana to latest version at time of PR which is 8.3.3
Includes a backup of all of the dashboards, however they will be persisted as they're stored in AWS EFS and attached to the running instance
Ensure Grafana is up, version can be seen at the bottom of the login page
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: gulp, …
> feat: cfd-584 upgrade Grafana version to 8.3.3

- repos/fdbt-site/src/utils/apiUtils/matching.ts
- repos/fdbt-site/tests/utils/api/matching.test.ts
-   Implement a custom master stop list algorithm when toposort fails
-   Try noc MBCH and so a Single for service 387. The master stop list should not have duplicates. …
> feat: cfd-591 - implement a custom master stop list algorithm when toposort fails

- fdbt-aws/cloudformation/service/eu-west-2/rds.yml
Setting RDS CPU Alarm to 95%
No nightly false positive alarm firing to Slack
- …
> fix: Setting RDS CPU Alarm to 95%

- fdbt-aws/cloudformation/service/eu-west-2/vpc.yml
fix: cfd-621 restricting database and bastion egress rules …
> fix: cfd-621 restricting database and bastion egress rules

- repos/fdbt-admin/customHttp.yml
fix: cfd-604 adding security headers to admin
Needs to be manually deployed in the Amplify Console due to outstanding `amplify` cli issue of not adding headers to existing deployments https://github.com/aws-amplify/amplify-console/issues/1317
-   [ ] ci - Changes to …
> fix: cfd-604 adding security headers to admin

- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/main.py
- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
fix: cfd-597 only close the db connection once
"Already closed" errors seen in test not seen again …
> fix: cfd-597 only close the db connection once

- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/main.py
Gets automatically closed
Nightly uploaders complete, need to trigger retrievers to then trigger Uploaders via S3 actions …
> fix: cfd-597 connection does not need closing

- fdbt-aws/cloudformation/service/us-east-1/lambda.yml
fix: cfd-545 allow csp all from self
* CloudFormation `fdbt-aws/cloudformation/service/us-east-1/lambda.yml` needs manually deploying. Then `FDBT-Cloudfront` stack updating with the Lambda version ARN (ensure a new version has been created)
* This will affect the CloudFront Error page, so need to break/disable Fargate site to see this error page
-   [ ] build - Changes that affect …
> fix: cfd-545 allow csp all from self

- fdbt-aws/cloudformation/service/eu-west-2/vpc.yml
allow ftp egress for retrievers
Any Lambda event will trigger the retriever
-   [ …
> fix: cfd-623 allow ftp egress for retrievers

- repos/fdbt-site/src/pages/pointToPointPeriodProduct.tsx
- repos/fdbt-site/tests/pages/__snapshots__/pointToPointPeriodProduct.test.tsx.snap
Point to Point Period should not have "No Expiry" option in dropdown
Boolean attributes in JSX default to true, which when `carnet` is passed to the `ExpirySelector` results in the `CarnetExpiryUnit` being used, which contains "No Expiry" not the `ExpiryUnit` which doesn't
User journey: Create a product > period ticket > point to point > follow the journey until -> Enter your period product details -> Period duration -> Confirm duration dropdown does not have "No Expiry"
> fix: cfd-493 Point to Point Period should not have "No Expiry" option

- repos/fdbt-admin/src/pages/ListUsers.tsx
User's with a lot of NOCs break the page width as the attribute is returned without spaces and cannot be broken up by the browser. So replace the `|` with `, ` so the browser can break it up and wrap it into the column of the list table
This change need manual deployments through `amplify publish` this will be picked up as part of the DNS migration work as that already contains a step to deploy to Admin
List users in Admin
> fix: cfd-643 fix noc attribute in admin

- repos/fdbt-site/cypress_tests/cypress/support/helpers.ts
- repos/fdbt-site/cypress_tests/cypress/support/steps.ts
fix: cfd-638 retry route selection if route cannot be used for return
Run ui tests
> fix: cfd-638 retry route selection if route cannot be used for return

- repos/fdbt-site/src/pages/api/selectPassengerType.ts
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/tests/pages/api/selectPassengerType.test.ts
- repos/fdbt-site/tests/pages/products/productDetails.test.tsx
To allow users to edit a passenger type without having to delete and recreate the product.
Run locally and edit a passenger type via My Fares.
> feat: Edit passenger type for products

- repos/fdbt-site/src/components/GenerateReturnPopup.tsx
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/interfaces/typeGuards.ts
- repos/fdbt-site/src/pages/api/generateReturn.ts
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/tests/components/GenerateReturnPopup.test.tsx
- repos/fdbt-site/tests/components/__snapshots__/GenerateReturnPopup.test.tsx.snap
- repos/fdbt-site/tests/pages/api/apiUtils/userData.test.ts
- repos/fdbt-site/tests/pages/api/csvUpload.test.ts
- repos/fdbt-site/tests/pages/api/generateReturn.test.ts
- repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap
- repos/fdbt-site/tests/pages/products/productDetails.test.tsx
- repos/fdbt-site/tests/testData/mockData.ts
Gives the user the ability to automatically create a return from two eligible singles for the same service, as long as they meet certain criteria.
Create two singles which use the same service, same passenger type (id), and have both outbound and inbound directions, and ensure they are not expired. Then find one of them, and click the generate button.
> feat: autogenerate returns from singles

- repos/fdbt-site/src/pages/inboundMatching.tsx
- repos/fdbt-site/src/utils/apiUtils/matching.ts
Fixed the direction in the inbound matching
Create a return ticket and select the service (which has both inbound and outbound). The inbound page should be showing the stops for inbound direction only.
> fix/CFDS-47: Fixed the direction for the inbound matching

- fdbt-dev/data/netexData/carnetFlatFare.xml
- fdbt-dev/data/netexData/carnetPeriodGeoZone.xml
- fdbt-dev/data/netexData/carnetPeriodMultiService.xml
- fdbt-dev/data/netexData/flatFare.xml
- fdbt-dev/data/netexData/flatFareGeoZone.xml
- fdbt-dev/data/netexData/flatFareGroup.xml
- fdbt-dev/data/netexData/flatFareWithSopPrices.xml
- fdbt-dev/data/netexData/hybridPeriod.xml
- fdbt-dev/data/netexData/multiOpGeoZone.xml
- fdbt-dev/data/netexData/multiOpMultiServices.xml
- fdbt-dev/data/netexData/periodGeoZone.xml
- fdbt-dev/data/netexData/periodGeoZoneGroup.xml
- fdbt-dev/data/netexData/periodMultiService.xml
- fdbt-dev/data/netexData/schemeCarnetFlatFare.xml
- fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml
- fdbt-dev/data/netexData/schemeCarnetPeriod.xml
- fdbt-dev/data/netexData/schemeOperatorFlatFare.xml
- fdbt-dev/data/netexData/schemeOperatorGeoZone.xml
- fdbt-dev/data/netexData/schemeOperatorMultiServices.xml
- fdbt-dev/data/netexData/schoolPeriodMultiService.xml
- repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
[CFDS-37](https://deliverybackbone.ema.kpmg.com/pdstudio86/browse/CFDS-37)
Currently flat fare user journey uses period ticket naming convention: {productName} Pass - {passengerType}
For flat fare ticket(any variation): Name under PreassignedFareProduct should be the same as pointToPoint ticket - productNameForPlainText
For period ticket (any variation): Name should be '{productName} - {passengerType}' e.g. remove the word Pass
Run the tests and code review
> Story CFDS-37 - PreassignedFareProduct Name

- fdbt-dev/data/netexData/carnetFlatFare.xml
- fdbt-dev/data/netexData/carnetPeriodGeoZone.xml
- fdbt-dev/data/netexData/carnetPeriodMultiService.xml
- fdbt-dev/data/netexData/carnetReturn.xml
- fdbt-dev/data/netexData/carnetSingle.xml
- fdbt-dev/data/netexData/flatFare.xml
- fdbt-dev/data/netexData/flatFareGeoZone.xml
- fdbt-dev/data/netexData/flatFareGroup.xml
- fdbt-dev/data/netexData/flatFareWithSopPrices.xml
- fdbt-dev/data/netexData/hybridPeriod.xml
- fdbt-dev/data/netexData/multiOpGeoZone.xml
- fdbt-dev/data/netexData/multiOpMultiServices.xml
- fdbt-dev/data/netexData/periodGeoZone.xml
- fdbt-dev/data/netexData/periodGeoZoneGroup.xml
- fdbt-dev/data/netexData/periodMultiService.xml
- fdbt-dev/data/netexData/periodPointToPoint.xml
- fdbt-dev/data/netexData/return.xml
- fdbt-dev/data/netexData/returnCircular.xml
- fdbt-dev/data/netexData/returnCircularGroup.xml
- fdbt-dev/data/netexData/schemeCarnetFlatFare.xml
- fdbt-dev/data/netexData/schemeCarnetMultipleServices.xml
- fdbt-dev/data/netexData/schemeCarnetPeriod.xml
- fdbt-dev/data/netexData/schemeOperatorFlatFare.xml
- fdbt-dev/data/netexData/schemeOperatorGeoZone.xml
- fdbt-dev/data/netexData/schemeOperatorMultiServices.xml
- fdbt-dev/data/netexData/schoolPeriodMultiService.xml
- fdbt-dev/data/netexData/single.xml
- fdbt-dev/data/netexData/singleGroup.xml
- fdbt-dev/data/netexData/singleGroupMultipleAdults.xml
- repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts
Tariff name wasnt being properly altered - it was only happening inside the Preassigned Fare Product.
Generate some netex, and observe that the name of the Tariff is 'Tariff for <product-name>' instead of only '<product-name>'.
> fix: fixing tariff name

- repos/fdbt-site/src/pages/fareType.tsx
- repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap
- repos/fdbt-site/tests/pages/fareType.test.tsx
Using process.env.STAGE instead of process.env.NODE_ENV because we can't use NODE_ENV cant be used in a .tsx file.
Deploy to test and observe the fareType page.
> fix: Updated logic for rendering multi operator options

- repos/fdbt-site/src/pages/multipleOperatorsServiceList.tsx
- repos/fdbt-site/tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
- repos/fdbt-site/tests/pages/multipleOperatorsServiceList.test.tsx
Removing TNDS button from browser as we are not using this functionality 
Go through the steps making a multi operator product you should notice that there is no TNDS button when you reach the /multiOperatorsServiceList path/page
> feat: Remove TNDS button from multiOperatorServiceList page

- fdbt-aws/cloudformation/service/eu-west-2/fargate.yml
- repos/fdbt-netex-output/src/data/s3.ts
- repos/fdbt-netex-output/src/netex-convertor/handler.test.ts
- repos/fdbt-netex-output/src/netex-convertor/handler.ts
- repos/fdbt-site/cypress_tests/cypress/e2e/carnet/scheme.cy.ts
- repos/fdbt-site/cypress_tests/cypress/e2e/multiOperator.cy.ts
- repos/fdbt-site/cypress_tests/cypress/e2e/scheme.cy.ts
- repos/fdbt-site/cypress_tests/cypress/support/e2e.ts
We have changed the way we name our generated netex files, instead going for a structure like this:
FX-PI-01_UK_MCTR_LINE-FARE_Best-Product_2022-10-18_2010-12-17.xml
And we add _1 or _2 etc if there are duplicates.
Locally, this code will not be ran - to ensure the make commands all still work (it would have to be edited to make it work with this change). Unit test coverage ensures that the path where it was saving the files should remain the same. There is some uncertainty around how this will affect scheme operators generating netex, but the current site doesn't support them fully anyway.
> feat: Altered netex file naming strategy 

- repos/fdbt-site/src/components/PassengerTypeCard.tsx
- repos/fdbt-site/src/pages/api/deletePassenger.ts
- repos/fdbt-site/src/pages/selectPassengerType.tsx
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
- repos/fdbt-site/tests/pages/__snapshots__/selectPassengerType.test.tsx.snap
Giving passenger type cards ID's so they can be referenced in errors.
Attempt to delete a passenger type that is being used by a product, and then click on the red error you are shown. It should snap the user's focus to the passenger type list.
> fix: Passenger type card ID's

- .github/workflows/fdbt-site_preprod_deployment.yml
- .github/workflows/fdbt-site_prod_deployment.yml
- .github/workflows/fdbt-site_test_deployment.yml
We were experiencing a bug which was fixed here https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/385 and trying to update to v1 to get the fix.
Deployment to test site should work.
> fix: Changed version of aws amazon ecs deploy task

- repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx
- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/pages/api/deletePurchaseMethod.ts
- repos/fdbt-site/src/pages/viewPurchaseMethods.tsx
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/components/__snapshots__/GlobalSettingsViewPage.test.tsx.snap
Currently we give a warning if the user attempts to delete a purchase method which is used in a product, but if they click delete then we delete it anyway. This causes an error later on.
We should instead just not let the user delete - if possible we should give the number of products the purchase type is connected to, so they can go and edit those products.
Case 1:
Make a product and connect it to a purchase method.
Try delete the purchase method.
An error message on the page should appear.
All valid examples:
You cannot delete 123 because it is being used in 3 products.
Case 2:
Make a purchase method alone that is not connected to a product.
Try deleting this.
It should be removed.
Note to add a purchase method navigate to View and manage fares > Operator settings > Purchase Methods
> Fix: Deleting Purchase Method breaks products

- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/pages/api/deletePassenger.ts
- repos/fdbt-site/src/pages/api/deletePurchaseMethod.ts
- repos/fdbt-site/src/pages/api/deleteTimeRestriction.ts
- repos/fdbt-site/src/pages/viewTimeRestrictions.tsx
- repos/fdbt-site/src/utils/sessions.ts
Currently we give a warning if the user attempts to delete a time restriction which is used in a product, but if they click delete then we delete it anyway. This causes an error later on.
We should instead just not let the user delete - if possible we should give the number of products the purchase type is connected to, so they can go and edit those products.
Case 1:
Make a product and connect it to a time restriction.
Try delete the time restriction.
An error message on the page should appear.
All valid examples:
You cannot delete 123 because it is being used in 3 product(s).
Case 2:
Make a time restriction alone that is not connected to a product.
Try deleting this.
It should be removed.
Note to add a time restriction navigate to View and manage fares > Operator settings > Time …
> fix: Deleting Time Restrictions Breaks Products

- repos/fdbt-site/src/data/s3.ts
- repos/fdbt-site/src/pages/api/deleteProduct.ts
- repos/fdbt-site/src/pages/globalSettings.tsx
- repos/fdbt-site/tests/pages/__snapshots__/globalSettings.test.tsx.snap
Previously when a product was being deleted, it was only being deleted from the DB and the s3 product was being left behind. 
Delete a product, and then check the s3 bucket to see if it was removed from there also.
> fix: Deleting products now deletes in S3

- fdbt-aws/cloudformation/service/eu-west-2/iam.yml
- repos/fdbt-site/src/pages/api/deleteProduct.ts
We cannot delete from the matching bucket for a product as we dont know the name of the export associated.
N/A
> fix: Removing deletion for matching bucket

- repos/fdbt-site/fdbt-types/matchingJsonTypes.ts
- repos/fdbt-site/src/pages/api/returnService.ts
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/tests/pages/api/returnService.test.ts
- repos/fdbt-site/tests/testData/mockData.ts
- repos/fdbt-types/matchingJsonTypes.ts
Product details page not loading when the multiple services are associated with the same lineId. The service Id to be used for fetching the service details in additional service for return ticket
Create a return ticket and add a service which has the lineId used in another service.
> fix: Product details page not loading for multiple services with lineId if adding service in return ticket

- fdbt-aws/cloudformation/service/eu-west-2/iam.yml
- repos/fdbt-site/src/data/s3.ts
- repos/fdbt-site/src/pages/api/getExportProgress.ts
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/tests/pages/products/__snapshots__/exports.test.tsx.snap
- repos/fdbt-site/tests/pages/products/exports.test.tsx
Stopping the user from cancelling the export until an hour has passed.
Run an export on test, wait until it has finished and then delete one of the .xml files from the netex s3 bucket relating to that export. An hour later, the cancel button should appear.
> fix: Added an hour check for when the user can cancel

- fdbt-dev/data/netexData/multiOpGeoZone.xml
- repos/fdbt-netex-output/src/netex-convertor/netexGenerator.ts
For multioperator geozone NeTEx fles, FareZone must have a specific type
Check generated netex for multioperator geozone NeTEx fles should have
```
<types>
<TypeOfZoneRef ref="fxc:fare_zone@multi_operator" version="fxc:v1.0"/>
</types>
```
> feat: FareZone Types

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/multipleOperatorsServiceList.tsx
- repos/fdbt-site/tests/pages/multipleOperatorsServiceList.test.tsx
This ticket remove duplicate Services from mulipleOperatorsServiceList
Services with uniq lineId, 
Start multi-operator journey and notice /mulipleOperatorsServiceList
> fix: Remove duplicates from multiple operator list

- repos/fdbt-netex-output/src/netex-convertor/handler.ts
- repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.test.ts
- repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts
The formatting on netex file names was using remove, which only removes the first instance of a character instead of all instances. The new function will remove all instances of a character from the string.
n/a.
> fix: Added remove all function

- repos/fdbt-site/cypress_tests/cypress/support/helpers.ts
- repos/fdbt-site/cypress_tests/cypress/support/steps.ts
- repos/fdbt-site/src/pages/selectPurchaseMethods.tsx
We need some UI tests for when a user edits parts of a ticket specific to non-point to point products, e.g.
- edit passenger type (validation in another ticket)
- edit time restriction (validation in another ticket)
- edit purchase methods (validation in another ticket)
Based on work https://github.com/fares-data-build-tool/create-data/pull/634
Run the UI tests and see if it enters the stated in the description
> feat: Rest of other product page UI tests

- repos/fdbt-site/cypress_tests/cypress/support/helpers.ts
Correcting other products page tests for edit services as it was failing for two cases (4 - Select all but the first case) and select all was causes an error where each checkobox was unclicked
Run the cypress tests for myFares.cy.ts it should pass
> fix: Correcting other products edit services

- fdbt-dev/data/netexData/carnetReturn.xml
- fdbt-dev/data/netexData/carnetSingle.xml
- fdbt-dev/data/netexData/periodPointToPoint.xml
- fdbt-dev/data/netexData/return.xml
- fdbt-dev/data/netexData/returnCircular.xml
- fdbt-dev/data/netexData/returnCircularGroup.xml
- fdbt-dev/data/netexData/returnWithExtraService.xml
- fdbt-dev/data/netexData/single.xml
- fdbt-dev/data/netexData/singleGroup.xml
- fdbt-dev/data/netexData/singleGroupMultipleAdults.xml
- repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.test.ts
- repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
All products require a ChargingMomentType within PreassignedFareProduct. 
This is present in some NeTEx outputs but is definitely missing from return tickets. We need to check each product to ensure it is present.
All products a user can currently create should have value of 'beforeTravel'.
Check generated netex for example similar to below:
`
<fareProducts>
<PreassignedFareProduct version="1.0" id="op:Pass@DayRider_adult">
<Name>DayRider</Name>
<ChargingMomentType>beforeTravel</ChargingMomentType>
<TypeOfFareProductRef version="fxc:v1.0" ref="fxc:standard_product@pass@period"/>
`
> feat: ChargingMomentType (current products)

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/data/s3.ts
- repos/fdbt-site/src/pages/api/getExportProgress.ts
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/src/utils/apiUtils/index.ts
- repos/fdbt-site/src/utils/index.ts
- repos/fdbt-site/tests/utils/index.test.ts
To display to the user the name of the failed files, when an export fails validation.
Simulate an export failing on test, and then click the button to view the names.
> feat: Display to user the name of failed export files

- .github/workflows/fdbt-site_test_deployment.yml
- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/pages/products/selectExports.tsx
On the /selectExports page, there was a DB call being made which could return multiple services as it was using the noc and lineId, but the code only ever expected one service to be returned. The change was to alter this DB call so multiple services can be returned, and the services are deduplicated so that we only show as many services as there needs to be on the page.
Using the data on test, create a single/return product for a service which has multiple versions in the DB (same lineId). Then, view that product in the selectExports page.
> fix: select exports page service change

- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/tests/pages/products/exports.test.tsx
As per title, removing isDevOrTest condition for the exports page, so the cancel exports button will show.
Cancel exports button should show on preprod and prod for failed exports.
> fix: Removed isDevOrTest condition in the exports page

- repos/fdbt-site/src/pages/api/reuseOperatorGroup.ts
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/tests/pages/api/reuseOperatorGroup.test.ts
- repos/fdbt-site/tests/pages/products/productDetails.test.tsx
If the product is a multi operator geoZone ticket, we should let the user edit which operator group it has assigned to it.
Create a multi operator geozone ticket and edit the 'Multi Operator Group'
Make sure you have at least two operator groups
> feat: Edit multi operator group for GeoZone ticket

- .github/workflows/fdbt-site_test_deployment.yml
- repos/fdbt-site/src/data/s3.ts
Altered S3 functions to use continuation tokens, which means more than 1000 objects can be returned from S3, and hence over 1000 products on the site can be returned.
On test, log into LNUD and check the pages where it loads the products / exports.
> feat: site supports over 1000 products

- docs/guides/getting-started.md
- repos/fdbt-site/src/pages/products/exports.tsx
If more than one file failed, the export tag says EXPORT FAILED - 3 FILES FAILED. It also says this if 1 file fails, and as such needed some editing. (EXPORT FAILED - 1 FILES FAILED).
View tag on an export where 1 file has failed.
> fix: spelling fix for exports page

- repos/fdbt-site/cypress_tests/browserstack.json
Changing spec timeout to prevent cypress tests from skipping on browserstack
Code review
> fix: change spec timeout

- repos/fdbt-site/src/pages/api/csvZoneUpload.ts
Removing any duplicated atco codes that get uploaded in a file.
Upload a csvZone with duplicate stop codes and observe it removes duplicates.
> fix: Deduplicated atcos using lodash/uniq

- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/constants/index.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/interfaces/matchingJsonTypes.ts
- repos/fdbt-site/src/pages/api/csvZoneUpload.ts
- repos/fdbt-site/src/pages/api/fareType.ts
- repos/fdbt-site/src/pages/api/serviceList.ts
- repos/fdbt-site/src/utils/apiUtils/index.ts
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/pages/api/csvZoneUpload.test.ts
- repos/fdbt-site/tests/pages/api/fareType.test.ts
- repos/fdbt-site/tests/pages/api/serviceList.test.ts
Fix the capped product journey for the ticket representation
Create a capped product and ticket representation page will appear after /fareConfirmation and will be redirected after selecting options in /ticketRepresentation to /typeOfCap
> fix: Capped product journey for ticket representation

- repos/fdbt-site/src/pages/selectTimeRestrictions.tsx
When a user creates a new product, the time restrictions page will default to no
Create a product see if time restrictions defaults to yes and check if edit defaults still work
> fix: Time restrictions always defaults to no on new journey

- repos/fdbt-reference-data-service/src/uploaders/txc_uploader/txc_processor.py
Error was being thrown "ERROR! Unexpected error. Could not write to database. Error: too many values to unpack (expected 10)" which is suspected to be because the check_txc_line_exists function calling extract_data_for_txc_operator_service_table did not have 11 arguments returning when it should have done, it only had 10 (hence the error we got saying it expected 10).
Testing will be done on test env by manually triggering data import.
> fix: Adding in mode to function

- repos/fdbt-site/src/pages/api/salesConfirmation.ts
In /salesConfirmation API we need to check to see if the ticket is capped, and if it is then just redirect to the success page (the green bannered page).
Code review
> feat: Allow capped products to bypass matching json

- repos/fdbt-site/src/pages/additionalPricingStructures.tsx
- repos/fdbt-site/src/pages/api/additionalPricingStructures.ts
- repos/fdbt-site/src/pages/capConfirmation.tsx
- repos/fdbt-site/tests/pages/__snapshots__/capConfirmation.test.tsx.snap
- repos/fdbt-site/tests/pages/api/additionalPricingStructures.test.ts
- repos/fdbt-site/tests/pages/capConfirmation.test.tsx
Showing the additional structuring in the cap confirmation
Create a capped ticket by the distance, taps, and price and check for additional structuring int the cap confirmation page
> fix: Showing the additional structuring in cap confirmation

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/api/fareType.ts
- repos/fdbt-site/src/pages/api/returnService.ts
- repos/fdbt-site/src/pages/multiOperatorServiceList.tsx
- repos/fdbt-site/src/pages/returnService.tsx
- repos/fdbt-site/src/pages/service.tsx
- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/tests/pages/__snapshots__/returnService.test.tsx.snap
- repos/fdbt-site/tests/pages/multipleOperatorsServiceList.test.tsx
- repos/fdbt-site/tests/pages/returnService.test.tsx
- repos/fdbt-site/tests/pages/service.test.tsx
- repos/fdbt-site/tests/pages/serviceList.test.tsx
Enabling the operators which do not have the BODS services but the TNDS service having multi modes.
Create the different kind of tickets like single, return, period with multi services, capped ticket and the multi-operator tickets for the operator as mentioned in the description.
> feat: Adding the new tnds services for modes

- repos/fdbt-site/src/pages/reuseOperatorGroup.tsx
- repos/fdbt-site/tests/pages/__snapshots__/reuseOperatorGroup.test.tsx.snap
Fixed spelling on reuseOperatorGroup
Code review
> fix: fixed spelling in reuseOperatorGroup

- fdbt-dev/data/netexData/carnetPeriodGeoZone.xml
- fdbt-dev/data/netexData/carnetPeriodMultiService.xml
- fdbt-dev/data/netexData/carnetReturn.xml
- fdbt-dev/data/netexData/carnetSingle.xml
- fdbt-dev/data/netexData/flatFareGeoZone.xml
- fdbt-dev/data/netexData/flatFareGroup.xml
- fdbt-dev/data/netexData/multiOpGeoZone.xml
- fdbt-dev/data/netexData/multiOpMultiServices.xml
- fdbt-dev/data/netexData/periodGeoZone.xml
- fdbt-dev/data/netexData/periodGeoZoneGroup.xml
- fdbt-dev/data/netexData/periodMultiService.xml
- fdbt-dev/data/netexData/periodPointToPoint.xml
- fdbt-dev/data/netexData/return.xml
- fdbt-dev/data/netexData/returnCircular.xml
- fdbt-dev/data/netexData/returnCircularGroup.xml
- fdbt-dev/data/netexData/returnWithExtraService.xml
- fdbt-dev/data/netexData/schemeOperatorGeoZone.xml
- fdbt-dev/data/netexData/schemeOperatorMultiServices.xml
- fdbt-dev/data/netexData/schoolPeriodMultiService.xml
- fdbt-dev/data/netexData/single.xml
- fdbt-dev/data/netexData/singleGroup.xml
- fdbt-dev/data/netexData/singleGroupMultipleAdults.xml
- repos/fdbt-netex-output/src/data/auroradb.test.ts
- repos/fdbt-netex-output/src/data/auroradb.ts
- repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
- repos/fdbt-netex-output/src/netex-convertor/point-to-point-tickets/pointToPointTicketNetexHelpers.ts
- repos/fdbt-netex-output/src/netex-convertor/sharedHelpers.ts
NeTEx created with time restrictions include an additional FareStructureElement to include the additional restrictions to access rights of product. This should only apply to the FareStructureElement that includes the qualityStructureFactors. The other FareStructureElements relating to access (i.e. include GenericParameterAssignments) should remain unchanged.
Currently this FareStructureElement includes: 
`<TypeOfFareStructureElementRef version="fxc:v1.0" ref="fxc:access"/>`
This needs to be replaced with:
`<TypeOfFareStructureElementRef version="fxc:v1.0" ref="fxc:access_when"/>`
Code review required
> feat: Off-peak NeTEx change

- repos/fdbt-site/src/pages/csvZoneUpload.tsx
- repos/fdbt-site/tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
When the user clicks 'unselect all' or 'select all' , there seems to be some sort of page refresh happening and unselect all doesn't unselect all the services.
Create a flat fare geozone and test adding / removing services
> fix: Csv zone upload select all button not working

- fdbt-dev/flatFareWithExemptions.json
- repos/fdbt-site/src/interfaces/matchingJsonTypes.ts
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/tests/pages/api/apiUtils/userData.test.ts
- repos/fdbt-site/tests/testData/mockData.ts
We need to add the exempted services for a geoZone ticket if the user selects them, so we can display them in the netex.
Code review
> feat: Add the exempted services to geoZone matching JSON

- fdbt-dev/data/netexData/flatFareWithExemptions.xml
- repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.test.ts
- repos/fdbt-netex-output/src/netex-convertor/period-tickets/periodTicketNetexHelpers.ts
There was an error when validating NeTEx file: LNUD/exports/LNUD_2023_01_26/FX-PI-01_UK_LNUD_NETWORK-FARE_Hybrid-product-1_2023-01-26_2010-10-13_126c.xml, error: Element '
{[http://www.netex.org.uk/netex]}
GenericParameterAssignment': Duplicate key-sequence ['Hybrid_product_1-groupsOfLinesWrapper', '1.0', '2'] in key identity-constraint '
{[http://www.netex.org.uk/netex]}
GenericParameterAssignment_AnyVersionedKey_ordered'., line 328
Add exempted services to hybridPeriod.json and generate netex, run validation.
> fix: Hybrid netex creates duplicate netex element

- repos/fdbt-site/src/interfaces/matchingJsonTypes.ts
- repos/fdbt-site/src/pages/ticketRepresentation.tsx
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/tests/pages/ticketRepresentation.test.tsx
- repos/fdbt-types/matchingJsonTypes.ts
PPD (priced by distance) products did not have the product name saved at the top level of the product, which meant that it wasn't being picked up in the netex converter where it is required to be.
Export a flat fare priced by distance ticket and examine netex. Also, ensure saved JSON has product name correctly.
> fix: Removed feature flag and saving product name correctly for PPD

- repos/fdbt-site/src/components/UserDataUploads.tsx
- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/src/interfaces/matchingJsonTypes.ts
- repos/fdbt-site/src/interfaces/typeGuards.ts
- repos/fdbt-site/src/pages/api/csvZoneUpload.ts
- repos/fdbt-site/src/pages/api/serviceList.ts
- repos/fdbt-site/src/pages/api/ticketRepresentation.ts
- repos/fdbt-site/src/pages/csvUpload.tsx
- repos/fdbt-site/src/pages/csvZoneUpload.tsx
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/src/pages/ticketConfirmation.tsx
- repos/fdbt-site/src/utils/apiUtils/fileUpload.ts
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/pages/__snapshots__/csvUpload.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/serviceList.test.tsx.snap
- repos/fdbt-site/tests/pages/api/csvZoneUpload.test.ts
- repos/fdbt-site/tests/pages/api/serviceList.test.ts
- repos/fdbt-site/tests/pages/api/ticketRepresentation.test.ts
- repos/fdbt-site/tests/pages/csvZoneUpload.test.tsx
- repos/fdbt-site/tests/pages/products/productDetails.test.tsx
- repos/fdbt-site/tests/pages/serviceList.test.tsx
- repos/fdbt-site/tests/pages/ticketConfirmation.test.tsx
Users can upload csv's of exempt stops when they create multi service tickets. Also made some minor changes like updating select all services button to use state etc.
Create a multi service ticket and use page extensively, trying different error states etc. Editing exempt stops also.
> feature: Added new functionality to exempt stops from multi service tickets

- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/tests/pages/__snapshots__/serviceList.test.tsx.snap
Exempt stops was defaulting to yes instead of no.
Ensure the radio button defaults to no instead of yes.
> fix: Fixed defaulting of the exempt stops radio buttons

- repos/fdbt-site/src/pages/csvZoneUpload.tsx
- repos/fdbt-site/src/pages/service.tsx
- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/tests/pages/serviceList.test.tsx
If the user creates a hybrid ticket, they can exempt lines that they also select later on, which causes issues in the netex. This change stops the user from being able to do so, and vice versa.
Try and exempt a line, and also select it as a selected service.
> fix: stop duplicate lines in hybrid exemptions

- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/pages/api/getExportProgress.ts
- repos/fdbt-site/src/pages/api/selectExports.ts
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/src/utils/apiUtils/index.ts
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/pages/api/selectExports.test.ts
- repos/fdbt-site/tests/pages/products/exports.test.tsx
- repos/fdbt-site/tests/utils/index.test.ts
Users should be unable to see the export button just after selecting the products to export
Click on few products to export and just after that, click on the Export all products. Now, the export all products button will not appear just after the select product export completed.
> fix: Not showing the export button after the select export

- fdbt-dev/sql/txcOperatorLine.sql
- repos/fdbt-site/src/pages/products/selectExports.tsx
- repos/fdbt-site/src/pages/salesConfirmation.tsx
- repos/fdbt-site/tests/pages/__snapshots__/salesConfirmation.test.tsx.snap
- repos/fdbt-site/tests/pages/products/__snapshots__/selectExports.test.tsx.snap
Double clicking on form submission buttons caused products to be created twice, or exports to 'double up'. Using an onSubmit to make the button disabled, we can prevent this.
Attempt to double click the final button when creating a products, or the export all button on the /selectExports page.
> fix: using an onSubmit to prevent double clicking

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/interfaces/index.ts
- repos/fdbt-site/tests/pages/api/fareType.test.ts
- repos/fdbt-site/tests/pages/api/register.test.ts
- repos/fdbt-site/tests/pages/csvZoneUpload.test.tsx
- repos/fdbt-site/tests/pages/home.test.tsx
- repos/fdbt-site/tests/pages/returnService.test.tsx
- repos/fdbt-site/tests/pages/service.test.tsx
- repos/fdbt-site/tests/pages/serviceList.test.tsx
- repos/fdbt-site/tests/utils/index.test.ts
Display the services for operator having source of data as tnds and the end date as null
Find the ferry operator with the service whose end date is not populated in db.
> fix: Showing the services when end type is null

- .github/workflows/fdbt-site_test_deployment.yml
- repos/fdbt-site/src/constants/attributes.ts
- repos/fdbt-site/src/pages/api/getExportProgress.ts
- repos/fdbt-site/src/pages/api/selectExports.ts
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/pages/products/exports.test.tsx
Due to a race condition, users could fire 2 exports at once by using the /selectExports page first. This has been stopped via a check in the server side props.
Once deployed, attempt to run 2 exports at once.
> fix: stopping users firing 2 exports at once

- repos/fdbt-site/src/pages/searchOperators.tsx
- repos/fdbt-site/tests/pages/__snapshots__/searchOperators.test.tsx.snap
- repos/fdbt-site/tests/pages/searchOperators.test.tsx
Duplicate keys in the html (during maps) was causing issues when operators had the same name. The fix was to move to use NOC as the unique key.
Use search operators page and add a group with operators of the same name.
> fix: search operators fix

- repos/fdbt-reference-data-service/src/retrievers/requirements.txt
- repos/fdbt-reference-data-service/src/uploaders/requirements.test.txt
- repos/fdbt-reference-data-service/src/uploaders/requirements.txt
[Urrllib3 docs](https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#migrating-as-an-application-developer)
As shown above botocore and requests need v2 of urllib
> fix: Downgrade urllib3 to v2

- repos/fdbt-site/src/pages/contact.tsx
- repos/fdbt-site/src/pages/home.tsx
- repos/fdbt-site/src/pages/multiOperatorServiceList.tsx
- repos/fdbt-site/src/pages/returnService.tsx
- repos/fdbt-site/src/pages/service.tsx
- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/tests/pages/__snapshots__/contact.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/returnService.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/service.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/serviceList.test.tsx.snap
For accessibility links must be more specific
EXPECTED:
[Content design: planning, writing and managing content - Links - Guidance - GOV.UK (www.gov.uk)](https://www.gov.uk/guidance/content-design/links#writing-link-text)
ACTUAL:
[Create Fares Data (dft-cfd.com)](https://preprod.dft-cfd.com/home) - If your query relates to the use of the Bus Open Data Service go [here](https://publish.bus-data.dft.gov.uk/) to view their contact details.
[Contact - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/contact) - To help improve the Create Fares Data service, send us your feedback [here](https://preprod.dft-cfd.com/feedback)
[Service - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/service) - This data is taken from the Bus Open Data Service (BODS). If …
> fix: Link texts

- repos/fdbt-site/src/layout/Layout.tsx
EXPECTED: Clicking tab after loading a landing page takes a user to the skip to main content button which should skip straight to the first header or actionable button in the main content. 
Open image-20240620-102948.png
image-20240620-102948.png
ACTUAL:
The link doesn't work either by clicking on the link with a cursor or pressing enter
STEPS TO REPRODUCE:
Load CFDS
click tab
click enter
What It Means
A skip navigation link exists, but the target for the link does not exist or the link is not keyboard accessible.
Why It Matters
A link to jump over navigation or jump to the main content of the page assists keyboard users only if the link is properly functioning and is keyboard accessible.
How to Fix It
Ensure that the target for the link exists and that the link is not hidden with CSS …
> fix: Skip to main content button does not work

- repos/fdbt-site/src/pages/csvZoneUpload.tsx
- repos/fdbt-site/src/pages/manageOperatorDetails.tsx
- repos/fdbt-site/src/pages/serviceList.tsx
- repos/fdbt-site/tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/serviceList.test.tsx.snap
EXPECTED
A fieldset legend presents a description of the form elements within a fieldset and is especially useful to screen reader users. A legend should be provided when a higher level description is necessary for groups of check boxes, radio buttons, or other form controls.
Standards and Guidelines
[1.1.1 Non-text Content (Level A)](https://webaim.org/standards/wcag/checklist#sc1.1.1)
[1.3.1 Info and Relationships (Level A)](https://webaim.org/standards/wcag/checklist#sc1.3.1)
[2.4.6 Headings and Labels (Level AA)](https://webaim.org/standards/wcag/checklist#sc2.4.6)
[3.3.2 Labels or Instructions (Level A)](https://webaim.org/standards/wcag/checklist#sc3.3.2)
ACTUAL
OCCURENCE 1 - [Service List - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/serviceList)
Open …
> fix: Missing Fieldset

- repos/fdbt-site/src/pages/manageTimeRestriction.tsx
- repos/fdbt-site/tests/pages/__snapshots__/manageTimeRestriction.test.tsx.snap
EXPECTED
A form control should have at most one associated label element. If more than one label element is associated to the control, assistive technology may not read the appropriate label.
ACTUAL
Two or more <label>s are associated to a single <input>
[Manage Time Restrictions - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/manageTimeRestriction)
Open image-20240624-153452.png
image-20240624-153452.png
‘USE FARE DAY END’
<div class="govuk-checkboxes__item item">
<input type="checkbox" class="govuk-checkboxes__input" name="fareDayEndmonday" id="use-fare-day-end">
<label class="govuk-label govuk-checkboxes__label" for="use-fare-day-end">
Use fare day end
</label>
</div>
PROPOSED SOLUTION:
Wrap the input within the label?
<label>
First Name
<input />
</label>
ELSE, …
> fix: Multiple form labels

- repos/fdbt-site/src/pages/searchOperators.tsx
- repos/fdbt-site/tests/pages/__snapshots__/searchOperators.test.tsx.snap
OCCURENCE 1 AND 2 DONE IN OTHER PRS
EXPECTED
example of correct use of form label:
<form>
<label for="name">Your Name:</label>
<input id="name" type="text" placeholder="Enter your Name">
<input type="submit" value="Submit"> 
</form>
ACTUAL
A form label is present, but it is not correctly associated with a form control.
OCCURENCE 1 - [Select Time Restrictions - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/selectTimeRestrictions)
Open image-20240624-100943.png
image-20240624-100943.png
<div class="govuk-radios govuk-radios--conditional" data-module="govuk-radios"><div class="govuk-radios__item">
<input type="radio" class="govuk-radios__input" id="valid-days-required" name="timeRestrictionChoice" value="Premade" aria-controls="conditional-time-restriction" …
> fix: Orphaned form label

- repos/fdbt-site/package-lock.json
- repos/fdbt-site/package.json
- repos/fdbt-site/src/components/DeleteConfirmationPopup.tsx
- repos/fdbt-site/src/components/GenerateReturnPopup.tsx
- repos/fdbt-site/src/components/GlobalSettingsViewPage.tsx
- repos/fdbt-site/src/components/InfoPopup.tsx
- repos/fdbt-site/src/components/ProductNamePopup.tsx
- repos/fdbt-site/src/components/Trap.tsx
- repos/fdbt-site/src/components/UnableToDeletePopup.tsx
- repos/fdbt-site/src/pages/manageFareDayEnd.tsx
- repos/fdbt-site/src/pages/manageOperatorDetails.tsx
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/src/pages/products/multiOperatorProducts.tsx
- repos/fdbt-site/src/pages/products/otherProducts.tsx
- repos/fdbt-site/src/pages/products/pointToPointProducts.tsx
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/pages/viewCaps.tsx
- repos/fdbt-site/src/pages/viewOperatorGroups.tsx
- repos/fdbt-site/src/pages/viewPassengerTypes.tsx
- repos/fdbt-site/src/pages/viewPurchaseMethods.tsx
- repos/fdbt-site/tests/components/GenerateReturnPopup.test.tsx
- repos/fdbt-site/tests/components/InfoPopup.test.tsx
- repos/fdbt-site/tests/components/__snapshots__/GenerateReturnPopup.test.tsx.snap
- repos/fdbt-site/tests/components/__snapshots__/InfoPopup.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/manageFareDayEnd.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/manageOperatorDetails.test.tsx.snap
EXPECTED - [3.2.2 On Input](https://www.w3.org/TR/WCAG22/#on-input)
When a user inputs information or interacts with a control, it does not result in a substantial change to the page, the spawning of a pop-up window, an additional change of keyboard focus, or any other change that could confuse or disorient the user unless the user is informed of the change ahead of time.
more about KB focus - [WebAIM: Keyboard Accessibility](https://webaim.org/techniques/keyboard/)
ACTUAL
OCCURENCE 1 - [Manage Fare Day End - Create Fares Data Service (dft-cfd.com)](https://preprod.dft-cfd.com/manageFareDayEnd)
clicking save:
Open image-20240626-085018.png
image-20240626-085018.png
Clicking tab until user reaches save button
pressing enter
keyboard focus is lost
clicking tab once reveals focus at the top …
> fix: focus on popups

- repos/fdbt-site/src/pages/api/ticketConfirmation.ts
- repos/fdbt-site/src/utils/apiUtils/index.ts
- repos/fdbt-site/tests/pages/api/ticketConfirmation.test.ts
Outcome
User should not be able to add caps to carnet products
Details 
Remove the page /selectCaps from all carnet product user journeys 
Create a cap
Go to create product create carnet type you should not see select caps page 
Go to single, return or flat fare generically and make a product after creating a cap you should see select cap
> feat: Remove caps for carnet journeys

- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/pages/salesConfirmation.tsx
- repos/fdbt-site/tests/pages/products/productDetails.test.tsx
- repos/fdbt-site/tests/pages/salesConfirmation.test.tsx
Caps should not show on review page for carnet types
Correcting https://github.com/fares-data-build-tool/create-data/pull/920
Check review page when making carnet ticket caps should not be present
> fix: Caps should not show on review page for carnet types

- repos/fdbt-site/src/pages/selectPurchaseMethods.tsx
- repos/fdbt-site/tests/pages/selectPurchaseMethods.test.tsx
Story
As a user, I would like to correctly define the purchase methods for individual products that qualify for a cap.
Details
We need to update the regular user journey to only show purchase methods defined in the ‘Capped purchase methods’ feature in the Operator Settings.  
Acceptance Criteria
When I am creating a fare product
Given I have select the ‘Yes’ on the /selectCaps page
When I am on /selectPurchaseMethods page
Then I should only see purchase methods I have defined on ‘Capped purchase methods’ feature on /viewPurchaseMethods page
> feat: Capped purchase methods should only show for caps

- repos/fdbt-site/src/layout/GlobalSettingReturnHeader.tsx
- repos/fdbt-site/src/pages/reuseOperatorGroup.tsx
- repos/fdbt-site/tests/pages/__snapshots__/reuseOperatorGroup.test.tsx.snap
**Occurrence 2 fixed in CFDS-278**
EXPECTED - [Broken ARIA Reference Explained - Make Your Website Accessible (equalizedigital.com)](https://equalizedigital.com/accessibility-checker/broken-aria-reference/)
example:
<div id="formBillingId">Billing</div>
<div>
<div id="formNameId">Name</div>
<input type="text" aria-labelledby="formBillingId formNameId"/>
</div>
<div>
<div id="formAddressId">Address</div>
<input type="text" aria-labelledby="formBillingId formAddressId"/>
</div>
ACTUAL
the aria-labelledby="..." seems to not match a listed variable in the code
OCCURENCE 1 - [Time restrictions (dft-cfd.com)](https://preprod.dft-cfd.com/viewTimeRestrictions)
<div class="govuk-notification-banner govuk-grid-row govuk-!-margin-top-5 govuk-!-margin-bottom-0" role="region" …
> fix: CFDS - Broken ARIA reference / Time Restrictions

- repos/fdbt-site/src/components/AccessibilityDetails.tsx
- repos/fdbt-site/src/design/modules/_helpers.scss
- repos/fdbt-site/src/pages/contact.tsx
- repos/fdbt-site/src/pages/csvUpload.tsx
- repos/fdbt-site/src/pages/csvZoneUpload.tsx
- repos/fdbt-site/src/pages/inputMethod.tsx
- repos/fdbt-site/tests/components/AccessibilityDetails.test.tsx
- repos/fdbt-site/tests/components/__snapshots__/AccessibilityDetails.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/contact.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/csvUpload.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/inputMethod.test.tsx.snap
- repos/fdbt-site/tests/pages/csvUpload.test.tsx
- repos/fdbt-site/tests/pages/csvZoneUpload.test.tsx
- repos/fdbt-site/tests/pages/inputMethod.test.tsx
Decided to add dropdowns rather than a link to a html page alternatives stored in sharepoint
EXPECTED:
PDFs on other government websites
Turn existing PDFs into HTML to improve accessibility and to reach as many users as possible. You need the source document to create an HTML webpage.
Creating a new document as PDF is a last resort and should be avoided unless there is a specific business need. You should always provide an HTML version too.
E.g.
Open image-20240621-084334.png
image-20240621-084334.png
[Publishing accessible documents - GOV.UK (www.gov.uk)](https://www.gov.uk/guidance/publishing-accessible-documents)
ACTUAL:
Open image-20240621-084407.png
image-20240621-084407.png
Open image-20240624-112944.png
image-20240624-112944.png
INSTANCES:
[Contact - Create Fares Data Service …
> fix: No HTML alternative provided for PDFs

- repos/fdbt-site/src/pages/selectCapExpiry.tsx
- repos/fdbt-site/src/pages/selectCaps.tsx
- repos/fdbt-site/src/pages/selectPassengerType.tsx
- repos/fdbt-site/src/pages/selectPeriodValidity.tsx
- repos/fdbt-site/tests/pages/__snapshots__/selectPassengerType.test.tsx.snap
During testing for accessibility PRs some bigs were found. The word "warning" was showing on warning text which should be hidden.
Orphaned form labels on the Caps page
> fix: accessibility bugs - hide warning text, fix orphaned form labels

- fdbt-dev/README.md
- repos/fdbt-site/README.md
- repos/fdbt-site/src/components/SettingOverview.tsx
- repos/fdbt-site/src/pages/home.tsx
- repos/fdbt-site/src/pages/products/exports.tsx
- repos/fdbt-site/src/pages/products/pointToPointProducts.tsx
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/pages/products/services.tsx
- repos/fdbt-site/tests/pages/__snapshots__/home.test.tsx.snap
- repos/fdbt-site/tests/pages/products/__snapshots__/pointToPointProducts.test.tsx.snap
- repos/fdbt-site/tests/pages/products/__snapshots__/productDetails.test.tsx.snap
- repos/fdbt-site/tests/pages/products/__snapshots__/services.test.tsx.snap
The GDS guidelines mention that uppercase text is harder to read. Since Gov UK tag examples use normal case, the tag casing has been updated.
Check tag casing in the following pages:
- home page when logged in
- services list
- select exports
> fix: do not use uppercase wording for tags

- repos/fdbt-site/src/pages/products/selectExports.tsx
The select exports page displays a count of all the user's products available for export, however this count includes invalid products that are not available to select. The fix is to omit invalid products from the count.
In pre-prod, the FSYO operator contains two invalid products and several valid products. Assert that the count of selected products matches the number of available products to select in the export tool. The count is in an indicator tag in the top-left of the page, e.g. "0 / 5 selected"
> fix: only map over valid products in exporter

- repos/fdbt-site/server/index.ts
- repos/fdbt-site/src/layout/Footer.tsx
- repos/fdbt-site/src/pages/changelog.tsx
- repos/fdbt-site/src/pages/index.tsx
- repos/fdbt-site/tests/layout/__snapshots__/Footer.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/changelog.test.tsx.snap
- repos/fdbt-site/tests/pages/__snapshots__/index.test.tsx.snap
- repos/fdbt-site/tests/pages/changelog.test.tsx
Add a service changelog to the site
- Go to "/changelog" and assert the page exists
- Assert the page has changelog content from 2024 onwards
- Assert the site footer has a "Service changelog" link to the changelog page
- Assert that on the home page under the main body, there is a link to the changelog page
> feat: add service changelog

- repos/fdbt-site/src/pages/fareType.tsx
- repos/fdbt-site/tests/pages/__snapshots__/fareType.test.tsx.snap
Amends text for the existing multi-operator option on the select fare type page
Assert that the multi-operator option label and supporting text matches the new text on the designs
> feat: amend multi-operator option text on fare type page

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/api/searchOperators.ts
- repos/fdbt-site/src/pages/products/multiOperatorProducts.tsx
- repos/fdbt-site/src/pages/products/multiOperatorProductsExternal.tsx
- repos/fdbt-site/src/pages/products/productDetails.tsx
- repos/fdbt-site/src/pages/products/selectExports.tsx
- repos/fdbt-site/src/pages/searchOperators.tsx
- repos/fdbt-site/src/pages/viewOperatorGroups.tsx
- repos/fdbt-site/tests/pages/__snapshots__/viewOperatorGroups.test.tsx.snap
- repos/fdbt-site/tests/pages/api/searchOperators.test.ts
- repos/fdbt-site/tests/pages/multipleProducts.test.tsx
- repos/fdbt-site/tests/pages/products/__snapshots__/selectExports.test.tsx.snap
- repos/fdbt-site/tests/pages/products/multiOperatorProducts.test.tsx
- repos/fdbt-site/tests/pages/products/multiOperatorProductsExternal.test.tsx
- repos/fdbt-site/tests/testData/mockData.ts
- editing operator groups now cascade changes into associated products
- for example, removing an operator from an operator group will mean that product no longer appears for that operator
- note that if an operator group is edited to include a new operator, and that group is associated with any multi-operator (internal) products that use selected services, then those products will have a new status "incomplete" until all the additional operator selected services are satisfied. At the moment the exporter will still export these products, however a future changes will filter out incomplete products when selecting products to export.
- adding operators to a group
- removing operators to a group
- both at the same time
> CFDS-315 operator group changes cascading to products

- fdbt-aws/sql/n.products.sql
- fdbt-dev/sql/products.sql
- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/api/reuseOperatorGroup.ts
- repos/fdbt-site/src/pages/api/searchOperators.ts
- repos/fdbt-site/src/pages/reuseOperatorGroup.tsx
- repos/fdbt-site/src/utils/apiUtils/userData.ts
- repos/fdbt-site/src/utils/sessions.ts
- repos/fdbt-site/tests/pages/api/reuseOperatorGroup.test.ts
- repos/fdbt-site/tests/pages/api/searchOperators.test.ts
When editing an operator group, updating associated products was broken because the only reference were noc codes which can be shared among multiple operator groups.
This PR introduces a proper operator group ID reference as a foreign key in the products table so that the correct products can be updated.
> feat: use operator group ID to ref associated products

- repos/fdbt-site/src/data/auroradb.ts
- repos/fdbt-site/src/pages/api/csvZoneUpload.ts
- repos/fdbt-site/src/pages/api/serviceList.ts
- repos/fdbt-site/src/utils/apiUtils/userData.ts
When creating a new multi-operator internal product that is a fare zone, the incomplete status is incorrectly set to true. This is caused by the fact that the `productAdditionalNocs` table is updated with additional nocs, and then incomplete status in the `products` table. The fix is to only update the `productAdditionalNocs` table for multi-operator external products upon product creation so that a multi-operator internal product can only have status incomplete if the product's operator group has a new operator added (after product creation).
> fix: prevent multi-operator internal status from being set wrong

- repos/fdbt-reference-data-service/src/uploaders/csv_uploader/db_queries.py
Reverting a change where we set character set as UTF-8 when inserting NOC data into DB as it produces an error.
> fix: revert character set utf8 change for noc queries
